// The project pane's graph-platform surface (#4227, epic #3604) — AUTO-GENERATED by
// scripts/gen-pane-graph.cjs. DO NOT EDIT BY HAND: it is derived from the VALUE imports the pane's
// records actually carry, so it cannot drift from them. Re-run the generator after changing the pane.
//
// Registered HERE, inside the feature, because the shell must not reach a feature's internals (#1545).
// It grew from the one entry #3901's survey left it with (`@/features/designs`) to the pane's whole
// reachable surface, because vendoring the pane into `planningpage` makes the LOADER responsible for
// every specifier it touches — the eleven stage bodies, the preview chain, the blueprint catalogue.
// While the pane was a registered code module, Vite had already bundled all of that.
//
// The pane's OWN modules are registered too: each is `provides`-resolved from the graph first, and the
// module behind it is the fallback for a record that will not load.
import { registerAppModule } from "@/shared/lib/runtime/moduleRegistry";
import * as Designs from "@/features/designs";
import * as BlueprintCatalog from "@/features/planner/blueprints/blueprintCatalog";
import * as BlueprintIcons from "@/features/planner/blueprints/blueprintIcons";
import * as DiscoveryBody from "@/features/planner/bodies/DiscoveryBody";
import * as FileIntakePane from "@/features/planner/bodies/FileIntakePane";
import * as FocusedAutomationsBody from "@/features/planner/bodies/FocusedAutomationsBody";
import * as FocusedFeaturesBody from "@/features/planner/bodies/FocusedFeaturesBody";
import * as FocusedSkillsBody from "@/features/planner/bodies/FocusedSkillsBody";
import * as FocusedSourceBody from "@/features/planner/bodies/FocusedSourceBody";
import * as MarketBody from "@/features/planner/bodies/MarketBody";
import * as McpsBody from "@/features/planner/bodies/McpsBody";
import * as ReposDeployView from "@/features/planner/bodies/ReposDeployView";
import * as StreamsBody from "@/features/planner/bodies/StreamsBody";
import * as TransformationsBody from "@/features/planner/bodies/TransformationsBody";
import * as FocusedHandlers from "@/features/planner/bodies/focusedHandlers";
import * as DirectorDrive from "@/features/planner/fleet/directorDrive";
import * as DeployConfig from "@/features/planner/lib/deployConfig";
import * as FocusedBodies from "@/features/planner/pane/FocusedBodies";
import * as FocusedShell from "@/features/planner/pane/FocusedShell";
import * as ProgressionRail from "@/features/planner/pane/ProgressionRail";
import * as FocusedPrimitives from "@/features/planner/pane/focusedPrimitives";
import * as ProjectPaneData from "@/features/planner/pane/projectPaneData";
import * as PreviewPaneShell from "@/features/planner/preview/PreviewPaneShell";
import * as RelationshipGraph from "@/features/planner/relationship/relationshipGraph";
import * as PlannerConductor from "@/features/planner/session/plannerConductor";
import * as Blueprints from "@/features/planner/stages/blueprints";
import * as FocusedPlan from "@/features/planner/stages/focusedPlan";
import * as StageGate from "@/features/planner/stages/stageGate";

let done = false;

/** Register the project pane's injected graph-platform modules. Idempotent. */
export function registerPanePlatform(): void {
  if (done) return;
  done = true;
  registerAppModule("@/features/designs", Designs);
  registerAppModule("@/features/planner/blueprints/blueprintCatalog", BlueprintCatalog);
  registerAppModule("@/features/planner/blueprints/blueprintIcons", BlueprintIcons);
  registerAppModule("@/features/planner/bodies/DiscoveryBody", DiscoveryBody);
  registerAppModule("@/features/planner/bodies/FileIntakePane", FileIntakePane);
  registerAppModule("@/features/planner/bodies/FocusedAutomationsBody", FocusedAutomationsBody);
  registerAppModule("@/features/planner/bodies/FocusedFeaturesBody", FocusedFeaturesBody);
  registerAppModule("@/features/planner/bodies/FocusedSkillsBody", FocusedSkillsBody);
  registerAppModule("@/features/planner/bodies/FocusedSourceBody", FocusedSourceBody);
  registerAppModule("@/features/planner/bodies/MarketBody", MarketBody);
  registerAppModule("@/features/planner/bodies/McpsBody", McpsBody);
  registerAppModule("@/features/planner/bodies/ReposDeployView", ReposDeployView);
  registerAppModule("@/features/planner/bodies/StreamsBody", StreamsBody);
  registerAppModule("@/features/planner/bodies/TransformationsBody", TransformationsBody);
  registerAppModule("@/features/planner/bodies/focusedHandlers", FocusedHandlers);
  registerAppModule("@/features/planner/fleet/directorDrive", DirectorDrive);
  registerAppModule("@/features/planner/lib/deployConfig", DeployConfig);
  registerAppModule("@/features/planner/pane/FocusedBodies", FocusedBodies);
  registerAppModule("@/features/planner/pane/FocusedShell", FocusedShell);
  registerAppModule("@/features/planner/pane/ProgressionRail", ProgressionRail);
  registerAppModule("@/features/planner/pane/focusedPrimitives", FocusedPrimitives);
  registerAppModule("@/features/planner/pane/projectPaneData", ProjectPaneData);
  registerAppModule("@/features/planner/preview/PreviewPaneShell", PreviewPaneShell);
  registerAppModule("@/features/planner/relationship/relationshipGraph", RelationshipGraph);
  registerAppModule("@/features/planner/session/plannerConductor", PlannerConductor);
  registerAppModule("@/features/planner/stages/blueprints", Blueprints);
  registerAppModule("@/features/planner/stages/focusedPlan", FocusedPlan);
  registerAppModule("@/features/planner/stages/stageGate", StageGate);
}
