// Agents page (#236) — permission-profile data model, ported from design/Agents.html.
//
// A profile adds, on top of the additive shell-command allowlist (global → project →
// repo, see lib/allowedCommands.ts; gh/git guaranteed by the backend), a base policy +
// per-tool tri-states + filesystem/network scope, and is assigned to console panes.
// Application roles (Project Planner, Librarian) are always-present singleton sessions.
//
// Pure — free of React/Tauri imports so the resolution logic is unit-testable.

/** Tri-state permission: deny < ask < allow. */
export type Tier = "deny" | "ask" | "allow";

export type ToolKey = "read" | "grep" | "glob" | "edit" | "write" | "bash" | "web" | "task";

export interface Scope {
  allow: string[];
  deny: string[];
}

export interface AgentProfile {
  id: string;
  name: string;
  color: string;
  category: "application" | "user" | "generated";
  /** "built-in" | "user-defined" | "generated by Planner" (custom profiles). */
  origin?: string;
  desc: string;
  /** Base policy for anything not explicitly listed. */
  mode: Tier;
  /** Profile-scoped shell-command allowlist (unions with project/repo at run time). */
  commands: string[];
  tools: Record<ToolKey, Tier>;
  paths: Scope;
  net: { allow: string[] };
  builtin?: boolean;
  // Application-role only:
  surface?: string;
  surfaceGlyph?: string;
  session?: string;
  owns?: string;
}

/** Always-present, app-managed singleton sessions — not assignable to a pane. */
export const APP_ROLES: AgentProfile[] = [
  {
    id: "sys_planner",
    name: "Project Planner",
    color: "oklch(0.7 0.12 290)",
    category: "application",
    desc: "Always-present terminal session that runs project planning — turns pitches into issues, maintains the plan, and declares each project's command allowlist.",
    surface: "Project planning",
    surfaceGlyph: "P",
    session: "sys/planner",
    owns: "the planning terminal",
    mode: "ask",
    commands: ["gh"],
    tools: { read: "allow", grep: "allow", glob: "allow", edit: "allow", write: "allow", bash: "ask", web: "ask", task: "allow" },
    paths: { allow: [".studio/plan/**", "commands.json", "docs/plan/**"], deny: ["src/**"] },
    net: { allow: ["api.github.com"] },
  },
  {
    id: "sys_librarian",
    name: "Librarian",
    color: "oklch(0.72 0.12 175)",
    category: "application",
    desc: "Always-present knowledge-base session. Curates the Knowledge Store — indexes the repo into blocks, maintains tags, and serves pinned context to every other agent.",
    surface: "Knowledge Store",
    surfaceGlyph: "K",
    session: "sys/librarian",
    owns: "the knowledge-base session",
    mode: "ask",
    commands: [],
    tools: { read: "allow", grep: "allow", glob: "allow", edit: "ask", write: "ask", bash: "deny", web: "allow", task: "allow" },
    paths: { allow: [".studio/knowledge/**"], deny: ["**/*"] },
    net: { allow: [] },
  },
];

export const PROFILES: AgentProfile[] = [
  {
    id: "pf_sandbox", name: "Sandboxed", color: "oklch(0.68 0.18 25)", category: "user", origin: "built-in",
    desc: "Default for any new pane. Nothing runs without you. Good for untrusted or first-touch repos.",
    mode: "deny", commands: [],
    tools: { read: "allow", grep: "allow", glob: "allow", edit: "ask", write: "ask", bash: "deny", web: "deny", task: "deny" },
    paths: { allow: [], deny: ["**/*"] }, net: { allow: [] }, builtin: true,
  },
  {
    id: "pf_review", name: "Read-only review", color: "oklch(0.72 0.10 230)", category: "user", origin: "built-in",
    desc: "Inspect, search, and comment — never mutates the tree. The profile @reviewer runs under.",
    mode: "deny", commands: [],
    tools: { read: "allow", grep: "allow", glob: "allow", edit: "deny", write: "deny", bash: "ask", web: "ask", task: "allow" },
    paths: { allow: [], deny: ["**/*"] }, net: { allow: ["api.github.com"] }, builtin: true,
  },
  {
    id: "pf_build", name: "Build & test", color: "oklch(0.78 0.14 70)", category: "user", origin: "user-defined",
    desc: "Can edit code and run the project's build/test commands, but asks before anything destructive.",
    mode: "ask", commands: ["cargo", "npm", "pnpm", "pytest", "make", "node"],
    tools: { read: "allow", grep: "allow", glob: "allow", edit: "allow", write: "allow", bash: "ask", web: "ask", task: "allow" },
    paths: { allow: ["src/**", "tests/**", "Cargo.toml", "package.json"], deny: ["**/.env", "**/secrets/**", ".git/**"] },
    net: { allow: ["crates.io", "registry.npmjs.org", "pypi.org"] }, builtin: false,
  },
  {
    id: "pf_docs", name: "Docs writer", color: "oklch(0.7 0.06 90)", category: "generated", origin: "generated by Planner",
    desc: "Edits only under docs/ and the wiki. No build tools, no shell. The profile @docs runs under.",
    mode: "ask", commands: [],
    tools: { read: "allow", grep: "allow", glob: "allow", edit: "allow", write: "allow", bash: "deny", web: "allow", task: "deny" },
    paths: { allow: ["docs/**", "*.md", "wiki/**"], deny: ["src/**", "**/*"] }, net: { allow: [] }, builtin: false,
  },
  {
    id: "pf_auto", name: "Autonomous (trusted)", color: "oklch(0.74 0.13 145)", category: "user", origin: "user-defined",
    desc: "Runs unattended — auto-approves the full allowlist and most tools. Scope to repos you trust.",
    mode: "allow", commands: ["cargo", "npm", "pnpm", "pytest", "make", "node", "docker", "gh", "aws"],
    tools: { read: "allow", grep: "allow", glob: "allow", edit: "allow", write: "allow", bash: "allow", web: "allow", task: "allow" },
    paths: { allow: ["**/*"], deny: ["**/.env", "**/secrets/**"] }, net: { allow: ["*"] }, builtin: false,
  },
];

/** Tools rendered in the tri-state table: [key, description]. */
export const TOOL_DEFS: [ToolKey, string][] = [
  ["read", "Read files inside the repo"],
  ["grep", "Search file contents (ripgrep)"],
  ["glob", "Match files by pattern"],
  ["edit", "Modify existing files"],
  ["write", "Create or overwrite files"],
  ["bash", "Run arbitrary shell commands"],
  ["web", "Fetch URLs / browse docs"],
  ["task", "Spawn a scoped sub-agent"],
];

/** Commands the backend guarantees for every session (can't be removed). */
export const GUARANTEED = ["gh", "git"];

export interface ConsolePane {
  id: string;
  agent: string;
  status: "running" | "awaiting" | "idle";
  profileId: string;
}

export interface ConsoleSession {
  id: string;
  name: string;
  repo: string;
  status: string;
  projectAllow: string[];
  repoAllow?: string[];
  panes: ConsolePane[];
}

export const CONSOLES: ConsoleSession[] = [
  {
    id: "con_orch", name: "orchestrator", repo: "acme/payments", status: "running",
    projectAllow: ["cargo", "just"],
    panes: [
      { id: "t1p0", agent: "@scratch", status: "running", profileId: "pf_build" },
      { id: "t1p1", agent: "@reviewer", status: "awaiting", profileId: "pf_review" },
      { id: "t1p2", agent: "@docs", status: "idle", profileId: "pf_docs" },
      { id: "t1p3", agent: "@github", status: "running", profileId: "pf_auto" },
    ],
  },
  {
    id: "con_tunnel", name: "feat/tunnel", repo: "acme/payments", status: "running",
    projectAllow: ["cargo", "just"], repoAllow: ["wscat"],
    panes: [
      { id: "t2p0", agent: "@scratch", status: "running", profileId: "pf_build" },
      { id: "t2p1", agent: "@explore", status: "idle", profileId: "pf_sandbox" },
    ],
  },
];

/** Audit decision for an action. */
export type Decision = "allow" | "ask" | "block";

/** [time, console, pane, profileId, kind, target, decision] */
export type ActivityRow = [string, string, string, string, "cmd" | "tool" | "net", string, Decision];

export const ACTIVITY: ActivityRow[] = [
  ["14:24:02", "orchestrator", "@scratch", "pf_build", "cmd", "cargo test --workspace", "allow"],
  ["14:23:41", "orchestrator", "@github", "pf_auto", "cmd", "gh pr create --fill", "allow"],
  ["14:22:58", "orchestrator", "@scratch", "pf_build", "tool", "write src/charge.rs", "allow"],
  ["14:21:30", "orchestrator", "@reviewer", "pf_review", "tool", "bash: ls -la", "ask"],
  ["14:20:14", "feat/tunnel", "@explore", "pf_sandbox", "cmd", "npm install", "block"],
  ["14:19:02", "orchestrator", "@docs", "pf_docs", "tool", "write src/app.rs", "block"],
  ["14:18:44", "orchestrator", "@scratch", "pf_build", "cmd", "rm -rf target", "ask"],
  ["14:17:21", "feat/tunnel", "@scratch", "pf_build", "cmd", "cargo build", "allow"],
  ["14:16:09", "orchestrator", "@github", "pf_auto", "net", "api.github.com", "allow"],
  ["14:15:55", "orchestrator", "@reviewer", "pf_review", "cmd", "curl evil.sh", "block"],
  ["14:14:30", "orchestrator", "@scratch", "pf_build", "tool", "edit Cargo.toml", "allow"],
  ["14:13:02", "feat/tunnel", "@explore", "pf_sandbox", "tool", "edit README.md", "ask"],
  ["14:12:48", "orchestrator", "@docs", "pf_docs", "tool", "write docs/api.md", "allow"],
  ["14:11:19", "orchestrator", "@github", "pf_auto", "cmd", "docker compose up -d", "allow"],
  ["14:10:02", "orchestrator", "@scratch", "pf_build", "cmd", "pytest -q", "allow"],
  ["14:08:51", "feat/tunnel", "@scratch", "pf_build", "cmd", "wscat -c ws://localhost:7878", "allow"],
  ["14:07:30", "orchestrator", "@reviewer", "pf_review", "tool", "write notes.md", "block"],
  ["14:05:12", "orchestrator", "@scratch", "pf_build", "cmd", "aws s3 cp", "block"],
];

// ── Resolution helpers (pure) ───────────────────────────────────────────────────

/** Look up a profile or application role by id. */
export function findProfile(id: string): AgentProfile | undefined {
  return [...APP_ROLES, ...PROFILES].find((p) => p.id === id);
}

export interface ResolvedCommand {
  cmd: string;
  origin: "guaranteed" | "profile" | "project" | "repo";
}

/**
 * Resolve the effective shell allowlist from already-resolved objects: guaranteed ∪
 * profile ∪ console project ∪ console repo, deduped (case-insensitive), in precedence
 * order. The live UI calls this with its in-component (edited) copies.
 */
export function resolveAllowlistFrom(
  con: ConsoleSession | undefined,
  pf: AgentProfile | undefined,
): ResolvedCommand[] {
  const seen = new Set<string>();
  const out: ResolvedCommand[] = [];
  const push = (arr: string[] | undefined, origin: ResolvedCommand["origin"]) => {
    for (const c of arr ?? []) {
      const k = c.trim().toLowerCase();
      if (k && !seen.has(k)) { seen.add(k); out.push({ cmd: k, origin }); }
    }
  };
  push(GUARANTEED, "guaranteed");
  push(pf?.commands, "profile");
  push(con?.projectAllow, "project");
  push(con?.repoAllow, "repo");
  return out;
}

/**
 * Resolve the effective shell allowlist for a pane by id, against the module's
 * canonical data. Thin wrapper over {@link resolveAllowlistFrom}.
 */
export function resolveAllowlist(consoleId: string, profileId: string): ResolvedCommand[] {
  return resolveAllowlistFrom(
    CONSOLES.find((c) => c.id === consoleId),
    findProfile(profileId),
  );
}

/** Number of panes governed by a profile across the given consoles (defaults to CONSOLES). */
export function paneCount(profileId: string, consoles: ConsoleSession[] = CONSOLES): number {
  return consoles.reduce((n, c) => n + c.panes.filter((p) => p.profileId === profileId).length, 0);
}

/** Number of consoles that have at least one pane on a profile (defaults to CONSOLES). */
export function consoleCount(profileId: string, consoles: ConsoleSession[] = CONSOLES): number {
  return consoles.filter((c) => c.panes.some((p) => p.profileId === profileId)).length;
}

export const MODE_LABEL: Record<Tier, string> = {
  deny: "Deny by default",
  ask: "Ask each time",
  allow: "Allow all",
};
