import { Card } from "@/shared/ui/data/Card";
import { Button } from "@/shared/ui/controls/Button";
import { Row } from "@/shared/ui/layout/Row";
import { Spacer } from "@/shared/ui/layout/Spacer";
import { Box } from "@/shared/ui/layout/Box";
import { Text } from "@/shared/ui/typography/Text";

// ── AI weekly digest (static — generated by Claude) ───────────────────────────

export function AISummary() {
  return (
    <Card style={{
      padding: "14px 18px",
      background: "linear-gradient(135deg, color-mix(in oklch, var(--accent), transparent 88%), var(--bg-panel) 60%)",
      border: "1px solid var(--accent-dim)",
    }}>
      <Row gap={12} align="stretch">
        <Box className="mono" bg="linear-gradient(135deg, var(--accent), oklch(0.62 0.14 50))" radius={7} style={{
          flexShrink: 0, width: 28, height: 28,
          color: "var(--on-accent)", fontWeight: 700, fontSize: 13,
          display: "flex", alignItems: "center", justifyContent: "center",
        }}>C</Box>
        <Box style={{ flex: 1, fontSize: 12, lineHeight: 1.6, color: "var(--fg-muted)" }}>
          <Row gap={8} align="baseline" style={{ marginBottom: 4 }}>
            <Text mono size={11} tone="accent" style={{ textTransform: "uppercase", letterSpacing: ".06em" }}>
              weekly digest · claude
            </Text>
            <Box as="span" className="hint">generated 02:00 today · run #14</Box>
            <Spacer />
            <Button variant="ghost" style={{ height: 22, fontSize: 10 }}>regenerate</Button>
          </Row>
          <p style={{ margin: 0 }}>
            Portfolio is on track — active projects are progressing against open milestones.
            Cross-project activity shows consistent momentum. Check upcoming milestones
            and velocity trends below for details.
          </p>
        </Box>
      </Row>
    </Card>
  );
}
