// Agents page (#236) — permission-profile data model, ported from design/Agents.html.
//
// A profile is the per-agent permission unit (#1457): its own shell-command allowlist
// (gh/git/bsc-plan guaranteed by the backend), a base policy + per-tool tri-states +
// filesystem/network scope. Assigned to console panes and applied at launch.
// Application roles (e.g. Project Planner) are always-present singleton sessions.
//
// The role/profile DEFINITIONS live as one JSON file per role under `src-tauri/data/roles/`,
// loaded at build time via `import.meta.glob` (mirrors `data/skills/`, #1715) — so the packaged
// set is data, edited without touching this module. Pure — free of React/Tauri imports so the
// resolution logic is unit-testable.

import { overlayGlob } from "@/shared/lib/core/configOverrides";

/** Tri-state permission: deny < ask < allow. */
export type Tier = "deny" | "ask" | "allow";

export type ToolKey = "read" | "grep" | "glob" | "edit" | "write" | "bash" | "web" | "task";

export interface Scope {
  allow: string[];
  deny: string[];
}

export interface AgentProfile {
  id: string;
  name: string;
  color: string;
  category: "application" | "user" | "generated";
  /** "built-in" | "user-defined" | "generated by Planner" (custom profiles). */
  origin?: string;
  desc: string;
  /** Base policy for anything not explicitly listed. */
  mode: Tier;
  /** Profile-scoped shell-command allowlist (unions with project/repo at run time). */
  commands: string[];
  tools: Record<ToolKey, Tier>;
  paths: Scope;
  net: { allow: string[] };
  builtin?: boolean;
  // Application-role only:
  surface?: string;
  surfaceGlyph?: string;
  session?: string;
  owns?: string;
}

// One JSON file per role under `src-tauri/data/roles/`, bundled at build time. Application roles
// (category "application") are the always-present singletons; every other entry is an assignable
// permission profile (the built-in set seeded into the store). Sorted by filename for a stable order.
const roleModules = import.meta.glob<{ default: AgentProfile }>("@data/roles/*.json", { eager: true });
const ALL_ROLES: AgentProfile[] = overlayGlob("roles", roleModules)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([, p]) => p);

/** Always-present, app-managed singleton sessions — not assignable to a pane. */
export const APP_ROLES: AgentProfile[] = ALL_ROLES.filter((r) => r.category === "application");

/** The assignable permission profiles (the packaged built-ins; user-created ones live in the store). */
export const PROFILES: AgentProfile[] = ALL_ROLES.filter((r) => r.category !== "application");

/** Profile ids retired from the packaged set — dropped from a persisted store on rehydrate. */
const RETIRED_PROFILE_IDS = new Set(["pf_build", "pf_docs"]);

/**
 * Reconcile a persisted profile list against the packaged built-ins (mirrors the blueprint
 * `refreshBuiltIns` migration): the built-ins always come FRESH from code (the role JSON), the
 * retired demos + any stale generated (`gen_*`) profiles are dropped, and the user's own custom
 * profiles are preserved. Run once in the store's `onRehydrateStorage`.
 */
export function reconcileBuiltInProfiles(stored: AgentProfile[]): AgentProfile[] {
  const builtinIds = new Set(PROFILES.map((p) => p.id));
  const customs = (stored ?? []).filter(
    (p) => !builtinIds.has(p.id) && p.category !== "generated" && !RETIRED_PROFILE_IDS.has(p.id),
  );
  return [...PROFILES, ...customs];
}

/** Tools rendered in the tri-state table: [key, description]. */
export const TOOL_DEFS: [ToolKey, string][] = [
  ["read", "Read files inside the repo"],
  ["grep", "Search file contents (ripgrep)"],
  ["glob", "Match files by pattern"],
  ["edit", "Modify existing files"],
  ["write", "Create or overwrite files"],
  ["bash", "Run arbitrary shell commands"],
  ["web", "Fetch URLs / browse docs"],
  ["task", "Spawn a scoped sub-agent"],
];

/** Commands the backend guarantees for every session (can't be removed). */
export const GUARANTEED = ["gh", "git"];

export interface ConsolePane {
  id: string;
  agent: string;
  status: "running" | "awaiting" | "idle";
  profileId: string;
}

export interface ConsoleSession {
  id: string;
  name: string;
  repo: string;
  status: string;
  projectAllow: string[];
  repoAllow?: string[];
  panes: ConsolePane[];
}

export const CONSOLES: ConsoleSession[] = [
  {
    id: "con_orch", name: "orchestrator", repo: "acme/payments", status: "running",
    projectAllow: ["cargo", "just"],
    panes: [
      { id: "t1p0", agent: "@scratch", status: "running", profileId: "pf_auto" },
      { id: "t1p1", agent: "@reviewer", status: "awaiting", profileId: "pf_review" },
      { id: "t1p2", agent: "@docs", status: "idle", profileId: "pf_review" },
      { id: "t1p3", agent: "@github", status: "running", profileId: "pf_auto" },
    ],
  },
  {
    id: "con_tunnel", name: "feat/tunnel", repo: "acme/payments", status: "running",
    projectAllow: ["cargo", "just"], repoAllow: ["wscat"],
    panes: [
      { id: "t2p0", agent: "@scratch", status: "running", profileId: "pf_auto" },
      { id: "t2p1", agent: "@explore", status: "idle", profileId: "pf_sandbox" },
    ],
  },
];

// ── Resolution helpers (pure) ───────────────────────────────────────────────────

/** Look up a profile or application role by id. */
export function findProfile(id: string): AgentProfile | undefined {
  return [...APP_ROLES, ...PROFILES].find((p) => p.id === id);
}

export interface ResolvedCommand {
  cmd: string;
  origin: "guaranteed" | "profile" | "project" | "repo";
}

/**
 * Resolve the effective shell allowlist from already-resolved objects: guaranteed ∪
 * profile ∪ console project ∪ console repo, deduped (case-insensitive), in precedence
 * order. The live UI calls this with its in-component (edited) copies.
 */
export function resolveAllowlistFrom(
  con: ConsoleSession | undefined,
  pf: AgentProfile | undefined,
): ResolvedCommand[] {
  const seen = new Set<string>();
  const out: ResolvedCommand[] = [];
  const push = (arr: string[] | undefined, origin: ResolvedCommand["origin"]) => {
    for (const c of arr ?? []) {
      const k = c.trim().toLowerCase();
      if (k && !seen.has(k)) { seen.add(k); out.push({ cmd: k, origin }); }
    }
  };
  push(GUARANTEED, "guaranteed");
  push(pf?.commands, "profile");
  push(con?.projectAllow, "project");
  push(con?.repoAllow, "repo");
  return out;
}

/**
 * Resolve the effective shell allowlist for a pane by id, against the module's
 * canonical data. Thin wrapper over {@link resolveAllowlistFrom}.
 */
export function resolveAllowlist(consoleId: string, profileId: string): ResolvedCommand[] {
  return resolveAllowlistFrom(
    CONSOLES.find((c) => c.id === consoleId),
    findProfile(profileId),
  );
}

/** Number of panes governed by a profile across the given consoles (defaults to CONSOLES). */
export function paneCount(profileId: string, consoles: ConsoleSession[] = CONSOLES): number {
  return consoles.reduce((n, c) => n + c.panes.filter((p) => p.profileId === profileId).length, 0);
}

/** Number of consoles that have at least one pane on a profile (defaults to CONSOLES). */
export function consoleCount(profileId: string, consoles: ConsoleSession[] = CONSOLES): number {
  return consoles.filter((c) => c.panes.some((p) => p.profileId === profileId)).length;
}

export const MODE_LABEL: Record<Tier, string> = {
  deny: "Deny by default",
  ask: "Ask each time",
  allow: "Allow all",
};
