// Agents page (#236) — permission-profile data model, ported from design/Agents.html.
//
// A profile is the per-agent permission unit (#1457): its own shell-command allowlist
// (gh/git/bsc-plan guaranteed by the backend), a base policy + per-tool tri-states +
// filesystem/network scope. Assigned to console panes and applied at launch.
// Application roles (e.g. Project Planner) are always-present singleton sessions.
//
// Pure — free of React/Tauri imports so the resolution logic is unit-testable.

/** Tri-state permission: deny < ask < allow. */
export type Tier = "deny" | "ask" | "allow";

export type ToolKey = "read" | "grep" | "glob" | "edit" | "write" | "bash" | "web" | "task";

export interface Scope {
  allow: string[];
  deny: string[];
}

export interface AgentProfile {
  id: string;
  name: string;
  color: string;
  category: "application" | "user" | "generated";
  /** "built-in" | "user-defined" | "generated by Planner" (custom profiles). */
  origin?: string;
  desc: string;
  /** Base policy for anything not explicitly listed. */
  mode: Tier;
  /** Profile-scoped shell-command allowlist (unions with project/repo at run time). */
  commands: string[];
  tools: Record<ToolKey, Tier>;
  paths: Scope;
  net: { allow: string[] };
  builtin?: boolean;
  // Application-role only:
  surface?: string;
  surfaceGlyph?: string;
  session?: string;
  owns?: string;
}

/** Always-present, app-managed singleton sessions — not assignable to a pane. */
export const APP_ROLES: AgentProfile[] = [
  {
    id: "sys_planner",
    name: "Project Planner",
    color: "oklch(0.7 0.12 290)",
    category: "application",
    desc: "Always-present terminal session that runs project planning — turns pitches into issues and maintains the plan.",
    surface: "Project planning",
    surfaceGlyph: "P",
    session: "sys/planner",
    owns: "the planning terminal",
    mode: "ask",
    commands: ["gh"],
    tools: { read: "allow", grep: "allow", glob: "allow", edit: "allow", write: "allow", bash: "ask", web: "ask", task: "allow" },
    paths: { allow: [".studio/plan/**", "docs/plan/**"], deny: ["src/**"] },
    net: { allow: ["api.github.com"] },
  },
  {
    // The Blueprint Assistant ("Design with Claude") is a STATELESS one-shot completion
    // (llm_complete) — it drafts/edits blueprint stages, prompts, and skills from a description.
    // It runs no shell, writes no files, and uses no tools, so its minimal role only really
    // governs what context it may read + net. Distinct from the Project Planner (#680).
    id: "sys_blueprint_assistant",
    name: "Blueprint Assistant",
    color: "oklch(0.7 0.13 330)",
    category: "application",
    desc: "Always-present design assistant for blueprints — a one-shot Claude that drafts and edits blueprint stages, prompts, and skills from your description. Read-only: it sees the active blueprint and the skills / knowledge library and returns suggestions; it runs no shell, writes no files, and has no tools.",
    surface: "Blueprints",
    surfaceGlyph: "B",
    session: "sys/blueprint-assistant",
    owns: "the blueprint design assistant",
    mode: "deny",
    commands: [],
    tools: { read: "allow", grep: "deny", glob: "deny", edit: "deny", write: "deny", bash: "deny", web: "deny", task: "deny" },
    paths: { allow: [], deny: ["**/*"] },
    net: { allow: [] },
  },
  {
    // The Planning Autopilot (#682) is the SIMULATED USER: a one-shot Claude that answers
    // the planner's discovery questions from the pitch so a plan can be produced hands-free.
    // Like the Blueprint Assistant it's a stateless completion — it reads the pitch + the
    // planner's output and returns a reply; no shell, no fs, no tools. Distinct from the
    // Project Planner (which it drives).
    id: "sys_planning_autopilot",
    name: "Planning Autopilot",
    color: "oklch(0.72 0.13 30)",
    category: "application",
    desc: "Answers the project planner's questions on your behalf, from the pitch, to drive a plan to completion hands-free. Read-only: it sees the pitch + the planner's output and replies; it runs no shell, writes no files, and has no tools.",
    surface: "Project planning",
    surfaceGlyph: "◇",
    session: "sys/planning-autopilot",
    owns: "the planning autopilot (simulated user)",
    mode: "deny",
    commands: [],
    tools: { read: "allow", grep: "deny", glob: "deny", edit: "deny", write: "deny", bash: "deny", web: "deny", task: "deny" },
    paths: { allow: [], deny: ["**/*"] },
    net: { allow: [] },
  },
];

/** The app role the planning autopilot's simulated user runs under (#682). */
export const PLANNING_AUTOPILOT_ROLE_ID = "sys_planning_autopilot";

export const PROFILES: AgentProfile[] = [
  {
    id: "pf_sandbox", name: "Sandboxed", color: "oklch(0.68 0.18 25)", category: "user", origin: "built-in",
    desc: "Default for any new pane. Nothing runs without you. Good for untrusted or first-touch repos.",
    mode: "deny", commands: [],
    tools: { read: "allow", grep: "allow", glob: "allow", edit: "ask", write: "ask", bash: "deny", web: "deny", task: "deny" },
    paths: { allow: [], deny: ["**/*"] }, net: { allow: [] }, builtin: true,
  },
  {
    id: "pf_review", name: "Read-only review", color: "oklch(0.72 0.10 230)", category: "user", origin: "built-in",
    desc: "Inspect, search, and comment — never mutates the tree. The profile @reviewer runs under.",
    mode: "deny", commands: [],
    tools: { read: "allow", grep: "allow", glob: "allow", edit: "deny", write: "deny", bash: "ask", web: "ask", task: "allow" },
    paths: { allow: [], deny: ["**/*"] }, net: { allow: ["api.github.com"] }, builtin: true,
  },
  {
    id: "pf_build", name: "Build & test", color: "oklch(0.78 0.14 70)", category: "user", origin: "user-defined",
    desc: "Can edit code and run the project's build/test commands, but asks before anything destructive.",
    mode: "ask", commands: ["cargo", "npm", "pnpm", "pytest", "make", "node"],
    tools: { read: "allow", grep: "allow", glob: "allow", edit: "allow", write: "allow", bash: "ask", web: "ask", task: "allow" },
    paths: { allow: ["src/**", "tests/**", "Cargo.toml", "package.json"], deny: ["**/.env", "**/secrets/**", ".git/**"] },
    net: { allow: ["crates.io", "registry.npmjs.org", "pypi.org"] }, builtin: false,
  },
  {
    id: "pf_docs", name: "Docs writer", color: "oklch(0.7 0.06 90)", category: "generated", origin: "generated by Planner",
    desc: "Edits only under docs/ and the wiki. No build tools, no shell. The profile @docs runs under.",
    mode: "ask", commands: [],
    tools: { read: "allow", grep: "allow", glob: "allow", edit: "allow", write: "allow", bash: "deny", web: "allow", task: "deny" },
    paths: { allow: ["docs/**", "*.md", "wiki/**"], deny: ["src/**", "**/*"] }, net: { allow: [] }, builtin: false,
  },
  {
    id: "pf_auto", name: "Autonomous (trusted)", color: "oklch(0.74 0.13 145)", category: "user", origin: "user-defined",
    desc: "Runs unattended — auto-approves the full allowlist and most tools. Scope to repos you trust.",
    mode: "allow", commands: ["cargo", "npm", "pnpm", "pytest", "make", "node", "docker", "gh", "aws"],
    tools: { read: "allow", grep: "allow", glob: "allow", edit: "allow", write: "allow", bash: "allow", web: "allow", task: "allow" },
    paths: { allow: ["**/*"], deny: ["**/.env", "**/secrets/**"] }, net: { allow: ["*"] }, builtin: false,
  },
];

/** Tools rendered in the tri-state table: [key, description]. */
export const TOOL_DEFS: [ToolKey, string][] = [
  ["read", "Read files inside the repo"],
  ["grep", "Search file contents (ripgrep)"],
  ["glob", "Match files by pattern"],
  ["edit", "Modify existing files"],
  ["write", "Create or overwrite files"],
  ["bash", "Run arbitrary shell commands"],
  ["web", "Fetch URLs / browse docs"],
  ["task", "Spawn a scoped sub-agent"],
];

/** Commands the backend guarantees for every session (can't be removed). */
export const GUARANTEED = ["gh", "git"];

export interface ConsolePane {
  id: string;
  agent: string;
  status: "running" | "awaiting" | "idle";
  profileId: string;
}

export interface ConsoleSession {
  id: string;
  name: string;
  repo: string;
  status: string;
  projectAllow: string[];
  repoAllow?: string[];
  panes: ConsolePane[];
}

export const CONSOLES: ConsoleSession[] = [
  {
    id: "con_orch", name: "orchestrator", repo: "acme/payments", status: "running",
    projectAllow: ["cargo", "just"],
    panes: [
      { id: "t1p0", agent: "@scratch", status: "running", profileId: "pf_build" },
      { id: "t1p1", agent: "@reviewer", status: "awaiting", profileId: "pf_review" },
      { id: "t1p2", agent: "@docs", status: "idle", profileId: "pf_docs" },
      { id: "t1p3", agent: "@github", status: "running", profileId: "pf_auto" },
    ],
  },
  {
    id: "con_tunnel", name: "feat/tunnel", repo: "acme/payments", status: "running",
    projectAllow: ["cargo", "just"], repoAllow: ["wscat"],
    panes: [
      { id: "t2p0", agent: "@scratch", status: "running", profileId: "pf_build" },
      { id: "t2p1", agent: "@explore", status: "idle", profileId: "pf_sandbox" },
    ],
  },
];

// ── Resolution helpers (pure) ───────────────────────────────────────────────────

/** Look up a profile or application role by id. */
export function findProfile(id: string): AgentProfile | undefined {
  return [...APP_ROLES, ...PROFILES].find((p) => p.id === id);
}

export interface ResolvedCommand {
  cmd: string;
  origin: "guaranteed" | "profile" | "project" | "repo";
}

/**
 * Resolve the effective shell allowlist from already-resolved objects: guaranteed ∪
 * profile ∪ console project ∪ console repo, deduped (case-insensitive), in precedence
 * order. The live UI calls this with its in-component (edited) copies.
 */
export function resolveAllowlistFrom(
  con: ConsoleSession | undefined,
  pf: AgentProfile | undefined,
): ResolvedCommand[] {
  const seen = new Set<string>();
  const out: ResolvedCommand[] = [];
  const push = (arr: string[] | undefined, origin: ResolvedCommand["origin"]) => {
    for (const c of arr ?? []) {
      const k = c.trim().toLowerCase();
      if (k && !seen.has(k)) { seen.add(k); out.push({ cmd: k, origin }); }
    }
  };
  push(GUARANTEED, "guaranteed");
  push(pf?.commands, "profile");
  push(con?.projectAllow, "project");
  push(con?.repoAllow, "repo");
  return out;
}

/**
 * Resolve the effective shell allowlist for a pane by id, against the module's
 * canonical data. Thin wrapper over {@link resolveAllowlistFrom}.
 */
export function resolveAllowlist(consoleId: string, profileId: string): ResolvedCommand[] {
  return resolveAllowlistFrom(
    CONSOLES.find((c) => c.id === consoleId),
    findProfile(profileId),
  );
}

/** Number of panes governed by a profile across the given consoles (defaults to CONSOLES). */
export function paneCount(profileId: string, consoles: ConsoleSession[] = CONSOLES): number {
  return consoles.reduce((n, c) => n + c.panes.filter((p) => p.profileId === profileId).length, 0);
}

/** Number of consoles that have at least one pane on a profile (defaults to CONSOLES). */
export function consoleCount(profileId: string, consoles: ConsoleSession[] = CONSOLES): number {
  return consoles.filter((c) => c.panes.some((p) => p.profileId === profileId)).length;
}

export const MODE_LABEL: Record<Tier, string> = {
  deny: "Deny by default",
  ask: "Ask each time",
  allow: "Allow all",
};
