//! The canonical registry of `bsc-*` sidecar CLIs (#1843).
//!
//! The set of sidecar CLIs the app ships — their names, `$BSC_*_BIN` env vars, project-store envs, and
//! one-line purposes — was hand-maintained in FOUR places that drifted independently:
//!   - `console/pty/mod.rs` (`wire_bsc_env`) — which `$BSC_*_BIN` to stage,
//!   - `console/shell_rc.rs` — the per-CLI shell helper that execs each sidecar,
//!   - `bsc-agent`'s `PROJECT_CLIS` — the "Project CLIs available this session" prompt block,
//!   - `bsc-agent/data/agent-instructions.md` — the prose list.
//!
//! This is the ONE source of truth all of them now read. Adding a CLI is a single row here; a shell_rc
//! regression test asserts every `standard_rc` sidecar still has its helper, so the list and the
//! helpers can't fall out of lockstep.

/// One `bsc-*` sidecar CLI: a bundled binary a live session reaches by an absolute path in `$BSC_*_BIN`
/// (no PATH changes), exposing one of the app's on-disk stores.
pub struct Sidecar {
    /// The command name (`bsc-plan`) — the shell-helper name and the agent's tool name.
    pub name: &'static str,
    /// The env var holding the staged binary's absolute path (`BSC_PLAN_BIN`); the shell helper execs
    /// `${BIN:-name}` and `wire_bsc_env` sets it when the sidecar is bundled.
    pub bin_env: &'static str,
    /// A *project*-scoped store env that must ALSO be set for this CLI to reach its data (`BSC_PLAN_DB`,
    /// `BSC_DATA_DB`). `None` for global stores (skill/compliance set their store env unconditionally)
    /// or none — so the agent prompt only flags "needs a project context" for the cwd-derived ones.
    pub context_env: Option<&'static str>,
    /// One-line purpose, shown to the agent in its CLI block.
    pub blurb: &'static str,
    /// Whether `bsc-agent` advertises this CLI in its prompt block + registers it as a directly-callable
    /// tool. `bsc-agent` itself is staged (so a session can relaunch the runtime) but never advertised.
    pub advertise: bool,
    /// Whether this CLI has the *standard* exec-rc shell helper (generated by `shell_rc`'s
    /// `bsc_sidecar_rc!` macro). `bsc-skill` has a bespoke helper (a different shape) and `bsc-agent`
    /// has none, so they are `false`. Drives the shell_rc drift-guard test.
    pub standard_rc: bool,
}

/// Every `bsc-*` sidecar the app can wire into a session. Order is the advertised set first (the order
/// the agent's CLI block renders), with the non-advertised `bsc-agent` runtime last. Staging reads the
/// whole set; the agent prompt reads the `advertise` subset; the shell_rc guard reads `standard_rc`.
pub const SIDECARS: &[Sidecar] = &[
    Sidecar {
        name: "bsc-plan", bin_env: "BSC_PLAN_BIN", context_env: Some("BSC_PLAN_DB"),
        blurb: "this project's plan store: issues, features, fleet streams, phases, prose sections",
        advertise: true, standard_rc: true,
    },
    Sidecar {
        name: "bsc-data", bin_env: "BSC_DATA_BIN", context_env: Some("BSC_DATA_DB"),
        blurb: "the Data Model + Platform Behavior Summary + entity tables; REST connectors",
        advertise: true, standard_rc: true,
    },
    Sidecar {
        name: "bsc-skill", bin_env: "BSC_SKILL_BIN", context_env: None,
        blurb: "the global skills library + task-groups",
        advertise: true, standard_rc: false, // bespoke helper (argc-dispatched), not the macro shape
    },
    Sidecar {
        name: "bsc-logs", bin_env: "BSC_LOGS_BIN", context_env: None,
        blurb: "query this session's logs (tools/skills/mcp/hooks/cost/coord/activity) + perf (read-only)",
        advertise: true, standard_rc: true,
    },
    Sidecar {
        name: "bsc-compliance", bin_env: "BSC_COMPLIANCE_BIN", context_env: None,
        blurb: "the compliance standards corpus (accessibility/privacy/security obligations)",
        advertise: true, standard_rc: true,
    },
    Sidecar {
        name: "bsc-blueprint", bin_env: "BSC_BLUEPRINT_BIN", context_env: None,
        blurb: "the user blueprint library",
        advertise: true, standard_rc: true,
    },
    Sidecar {
        name: "bsc-project", bin_env: "BSC_PROJECT_BIN", context_env: None,
        blurb: "list local projects + read/set the published marker",
        advertise: true, standard_rc: true,
    },
    Sidecar {
        name: "bsc-files", bin_env: "BSC_FILES_BIN", context_env: None,
        blurb: "the project's file tree with metrics + single-path stat",
        advertise: true, standard_rc: true,
    },
    Sidecar {
        name: "bsc-agent", bin_env: "BSC_AGENT_BIN", context_env: None,
        blurb: "the model-agnostic agent runtime (staged for relaunch; not self-advertised)",
        advertise: false, standard_rc: false,
    },
];

// ── Bundled MCP-server binaries (#1848) ──────────────────────────────────────────────
//
// The two bundled native MCP servers are app-shipped binaries resolved by the SAME `sidecar_bin_path`
// lookup as the CLIs above, but they aren't CLIs: no `$BSC_*_BIN` staging and no shell helper — Claude
// Code spawns them directly from `.mcp.json`, where the app substitutes the binary's absolute path for
// a sentinel marker. They live here so the inventory of every app-shipped binary (CLIs + MCP servers)
// is ONE list, and each server's name is defined ONCE — referenced by the pty path wrappers and the
// `extensions/mcp.rs` markers instead of being re-typed in each.

/// The bundled Research MCP server (#1196) — the `.mcp.json` sentinel + the `sidecar_bin_path` stem.
pub const RESEARCH_MCP: &str = "bsc-research-mcp";
/// The bundled Compliance MCP server (#1005) — the `.mcp.json` sentinel + the `sidecar_bin_path` stem.
pub const COMPLIANCE_MCP: &str = "bsc-compliance-mcp";

/// One bundled native MCP server: a binary shipped beside the app exe, spawned by Claude Code from
/// `.mcp.json` (its absolute path substituted for the `name` sentinel at write time).
pub struct BundledMcp {
    /// The binary stem (`bsc-research-mcp`) — both the `sidecar_bin_path` lookup and the `.mcp.json`
    /// command sentinel the app rewrites to the resolved absolute path.
    pub name: &'static str,
    /// One-line purpose (docs).
    pub purpose: &'static str,
}

/// Every bundled MCP-server binary the app ships.
pub const BUNDLED_MCP_SERVERS: &[BundledMcp] = &[
    BundledMcp { name: RESEARCH_MCP, purpose: "literature research over scholarly sources" },
    BundledMcp { name: COMPLIANCE_MCP, purpose: "the compliance standards corpus" },
];

/// Every app-shipped `bsc-*` binary's stem — the CLIs (`SIDECARS`) plus the bundled MCP servers — the
/// ONE inventory of binaries `sidecar_bin_path` can resolve beside the app exe.
pub fn all_bundled_names() -> Vec<&'static str> {
    SIDECARS.iter().map(|s| s.name).chain(BUNDLED_MCP_SERVERS.iter().map(|m| m.name)).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn registry_is_internally_consistent() {
        // Names are the bsc-* commands; bin_envs are the matching BSC_*_BIN, both unique.
        let mut names = std::collections::HashSet::new();
        let mut bins = std::collections::HashSet::new();
        for s in SIDECARS {
            assert!(s.name.starts_with("bsc-"), "{} is not a bsc-* command", s.name);
            assert!(s.bin_env.starts_with("BSC_") && s.bin_env.ends_with("_BIN"), "{} bad bin_env", s.name);
            assert!(names.insert(s.name), "duplicate name {}", s.name);
            assert!(bins.insert(s.bin_env), "duplicate bin_env {}", s.bin_env);
        }
    }

    #[test]
    fn only_cwd_derived_project_stores_carry_a_context_env() {
        // The agent prompt's "needs a project context" caveat must fire ONLY for the two cwd-derived
        // project stores; the global/none CLIs must not be flagged.
        for s in SIDECARS {
            let scoped = matches!(s.name, "bsc-plan" | "bsc-data");
            assert_eq!(s.context_env.is_some(), scoped, "{} context_env scoping wrong", s.name);
        }
        assert_eq!(SIDECARS.iter().find(|s| s.name == "bsc-plan").unwrap().context_env, Some("BSC_PLAN_DB"));
        assert_eq!(SIDECARS.iter().find(|s| s.name == "bsc-data").unwrap().context_env, Some("BSC_DATA_DB"));
    }

    #[test]
    fn advertised_and_standard_rc_subsets_match_the_known_sets() {
        let advertised: Vec<&str> = SIDECARS.iter().filter(|s| s.advertise).map(|s| s.name).collect();
        assert_eq!(
            advertised,
            ["bsc-plan", "bsc-data", "bsc-skill", "bsc-logs", "bsc-compliance", "bsc-blueprint", "bsc-project", "bsc-files"],
            "the advertised set + order is what the agent prompt block renders",
        );
        // bsc-agent is staged but never advertised.
        assert!(!SIDECARS.iter().find(|s| s.name == "bsc-agent").unwrap().advertise);
        // standard_rc excludes bsc-skill (bespoke) and bsc-agent (none).
        assert!(!SIDECARS.iter().find(|s| s.name == "bsc-skill").unwrap().standard_rc);
        assert!(!SIDECARS.iter().find(|s| s.name == "bsc-agent").unwrap().standard_rc);
    }

    #[test]
    fn bundled_mcp_servers_are_named_and_distinct_from_the_clis() {
        // #1848: the two bundled MCP servers are first-class registry entries; their names are the
        // single source the pty path-wrappers + the extensions/mcp.rs markers reference.
        let mcp: Vec<&str> = BUNDLED_MCP_SERVERS.iter().map(|m| m.name).collect();
        assert_eq!(mcp, [RESEARCH_MCP, COMPLIANCE_MCP]);
        for m in BUNDLED_MCP_SERVERS {
            assert!(m.name.starts_with("bsc-") && m.name.ends_with("-mcp"), "{} bad mcp name", m.name);
        }
        // The unified inventory is the CLIs + the MCP servers, with no overlap.
        let all = all_bundled_names();
        let unique: std::collections::HashSet<&str> = all.iter().copied().collect();
        assert_eq!(all.len(), unique.len(), "no bundled binary appears twice");
        assert!(all.contains(&RESEARCH_MCP) && all.contains(&COMPLIANCE_MCP));
        assert!(all.contains(&"bsc-plan"), "the CLIs are part of the one inventory too");
        // MCP servers are NOT CLIs — never in SIDECARS (so never staged as $BSC_*_BIN / advertised).
        assert!(!SIDECARS.iter().any(|s| s.name == RESEARCH_MCP || s.name == COMPLIANCE_MCP));
    }
}
