import { describe, it, expect } from "vitest";
import { generateAgentProfile } from "../lib/profileGen";
import type { AgentStream } from "../screens/projects/planSections";

const stream: AgentStream = {
  id: "be", name: "API backend", repo: "o/api",
  owns: ["src/api/**", "src/db/**"], issues: ["#1"], dependsOn: [],
};

describe("generateAgentProfile (#289)", () => {
  it("a worker can edit/write, scoped to its owned globs, with the toolchain", () => {
    const p = generateAgentProfile(stream, "worker", ["cargo", "npm", "cargo"]);
    expect(p).toMatchObject({ id: "gen_be", category: "generated", origin: "generated by Planner", mode: "ask" });
    expect(p.commands).toEqual(["cargo", "npm"]);          // deduped + sorted
    expect(p.tools.edit).toBe("allow");
    expect(p.tools.write).toBe("allow");
    expect(p.paths.allow).toEqual(["src/api/**", "src/db/**"]); // write scope = owns
  });

  it("a tester is read-only: no edit/write, no write paths, but may run the toolchain", () => {
    const p = generateAgentProfile(stream, "tester", ["npm test"]);
    expect(p.tools.edit).toBe("deny");
    expect(p.tools.write).toBe("deny");
    expect(p.tools.bash).toBe("allow");   // runs tests
    expect(p.paths.allow).toEqual([]);    // read-only ⇒ no write scope
    expect(p.commands).toEqual(["npm test"]);
  });

  it("trims/dedupes/sorts the discovered commands and tolerates empties", () => {
    const p = generateAgentProfile(stream, "worker", [" npm ", "npm", "", "cargo"]);
    expect(p.commands).toEqual(["cargo", "npm"]);
  });
});
