// The settings feature's graph-platform surface (#3658, epic #3604) — AUTO-GENERATED by
// scripts/gen-settings-graph.cjs. The setting CARDS + the two page helpers stay CODE: a graph-loaded
// Settings page composes them but does not redraw them (they run as normal registered modules). Registered
// HERE, inside the feature, because the shell must not reach a feature's internals (#1545). The settings
// host calls this synchronously before the graph page loads. Mirrors the other feature graph-platforms.
import { registerAppModule } from "@/shared/lib/runtime/moduleRegistry";
import * as AccentColorCard from "@/features/settings/cards/AccentColorCard";
import * as AchievementsCard from "@/features/settings/cards/AchievementsCard";
import * as AgentRolesCard from "@/features/settings/cards/AgentRolesCard";
import * as AgentsCard from "@/features/settings/cards/AgentsCard";
import * as ClaudeConfigCard from "@/features/settings/cards/ClaudeConfigCard";
import * as ConfigBundleCard from "@/features/settings/cards/ConfigBundleCard";
import * as ConnectGithubCard from "@/features/settings/cards/ConnectGithubCard";
import * as ConsolePageCard from "@/features/settings/cards/ConsolePageCard";
import * as DebugSessionCard from "@/features/settings/cards/DebugSessionCard";
import * as DefaultModelCard from "@/features/settings/cards/DefaultModelCard";
import * as DemoStateCard from "@/features/settings/cards/DemoStateCard";
import * as DiagnosticsCard from "@/features/settings/cards/DiagnosticsCard";
import * as IdleReaperCard from "@/features/settings/cards/IdleReaperCard";
import * as IssueSecurityCard from "@/features/settings/cards/IssueSecurityCard";
import * as KeyboardCard from "@/features/settings/cards/KeyboardCard";
import * as KitChangeApprovalCard from "@/features/settings/cards/KitChangeApprovalCard";
import * as KitThemeCard from "@/features/settings/cards/KitThemeCard";
import * as LlmProviderCard from "@/features/settings/cards/LlmProviderCard";
import * as LogsInventoryCard from "@/features/settings/cards/LogsInventoryCard";
import * as LogsRetentionCard from "@/features/settings/cards/LogsRetentionCard";
import * as LogsViewerCard from "@/features/settings/cards/LogsViewerCard";
import * as MetricsCollectionCard from "@/features/settings/cards/MetricsCollectionCard";
import * as PerfRetentionCard from "@/features/settings/cards/PerfRetentionCard";
import * as PermissionPostureCard from "@/features/settings/cards/PermissionPostureCard";
import * as PlanningAutomationCard from "@/features/settings/cards/PlanningAutomationCard";
import * as RepoCredentialsCard from "@/features/settings/cards/RepoCredentialsCard";
import * as SandboxDependencyCard from "@/features/settings/cards/SandboxDependencyCard";
import * as SandboxedConsolesCard from "@/features/settings/cards/SandboxedConsolesCard";
import * as SessionLogCard from "@/features/settings/cards/SessionLogCard";
import * as SessionsBehaviorCard from "@/features/settings/cards/SessionsBehaviorCard";
import * as ShellSelectorCard from "@/features/settings/cards/ShellSelectorCard";
import * as SoundNotificationsCard from "@/features/settings/cards/SoundNotificationsCard";
import * as StorageCard from "@/features/settings/cards/StorageCard";
import * as StudioCard from "@/features/settings/cards/StudioCard";
import * as TerminalFontSizeCard from "@/features/settings/cards/TerminalFontSizeCard";
import * as ThemeCard from "@/features/settings/cards/ThemeCard";
import * as WorkspaceCard from "@/features/settings/cards/WorkspaceCard";
import * as SettingsPageHeader from "@/features/settings/pages/SettingsPageHeader";
import * as tunnel from "@/features/tunnel";

let done = false;

/** Register the settings page's injected graph-platform modules (cards + page helpers). Idempotent. */
export function registerSettingsPlatform(): void {
  if (done) return;
  done = true;
  registerAppModule("@/features/settings/cards/AccentColorCard", AccentColorCard);
  registerAppModule("@/features/settings/cards/AchievementsCard", AchievementsCard);
  registerAppModule("@/features/settings/cards/AgentRolesCard", AgentRolesCard);
  registerAppModule("@/features/settings/cards/AgentsCard", AgentsCard);
  registerAppModule("@/features/settings/cards/ClaudeConfigCard", ClaudeConfigCard);
  registerAppModule("@/features/settings/cards/ConfigBundleCard", ConfigBundleCard);
  registerAppModule("@/features/settings/cards/ConnectGithubCard", ConnectGithubCard);
  registerAppModule("@/features/settings/cards/ConsolePageCard", ConsolePageCard);
  registerAppModule("@/features/settings/cards/DebugSessionCard", DebugSessionCard);
  registerAppModule("@/features/settings/cards/DefaultModelCard", DefaultModelCard);
  registerAppModule("@/features/settings/cards/DemoStateCard", DemoStateCard);
  registerAppModule("@/features/settings/cards/DiagnosticsCard", DiagnosticsCard);
  registerAppModule("@/features/settings/cards/IdleReaperCard", IdleReaperCard);
  registerAppModule("@/features/settings/cards/IssueSecurityCard", IssueSecurityCard);
  registerAppModule("@/features/settings/cards/KeyboardCard", KeyboardCard);
  registerAppModule("@/features/settings/cards/KitChangeApprovalCard", KitChangeApprovalCard);
  registerAppModule("@/features/settings/cards/KitThemeCard", KitThemeCard);
  registerAppModule("@/features/settings/cards/LlmProviderCard", LlmProviderCard);
  registerAppModule("@/features/settings/cards/LogsInventoryCard", LogsInventoryCard);
  registerAppModule("@/features/settings/cards/LogsRetentionCard", LogsRetentionCard);
  registerAppModule("@/features/settings/cards/LogsViewerCard", LogsViewerCard);
  registerAppModule("@/features/settings/cards/MetricsCollectionCard", MetricsCollectionCard);
  registerAppModule("@/features/settings/cards/PerfRetentionCard", PerfRetentionCard);
  registerAppModule("@/features/settings/cards/PermissionPostureCard", PermissionPostureCard);
  registerAppModule("@/features/settings/cards/PlanningAutomationCard", PlanningAutomationCard);
  registerAppModule("@/features/settings/cards/RepoCredentialsCard", RepoCredentialsCard);
  registerAppModule("@/features/settings/cards/SandboxDependencyCard", SandboxDependencyCard);
  registerAppModule("@/features/settings/cards/SandboxedConsolesCard", SandboxedConsolesCard);
  registerAppModule("@/features/settings/cards/SessionLogCard", SessionLogCard);
  registerAppModule("@/features/settings/cards/SessionsBehaviorCard", SessionsBehaviorCard);
  registerAppModule("@/features/settings/cards/ShellSelectorCard", ShellSelectorCard);
  registerAppModule("@/features/settings/cards/SoundNotificationsCard", SoundNotificationsCard);
  registerAppModule("@/features/settings/cards/StorageCard", StorageCard);
  registerAppModule("@/features/settings/cards/StudioCard", StudioCard);
  registerAppModule("@/features/settings/cards/TerminalFontSizeCard", TerminalFontSizeCard);
  registerAppModule("@/features/settings/cards/ThemeCard", ThemeCard);
  registerAppModule("@/features/settings/cards/WorkspaceCard", WorkspaceCard);
  registerAppModule("@/features/settings/pages/SettingsPageHeader", SettingsPageHeader);
  registerAppModule("@/features/tunnel", tunnel);
}
