// Planner-generated least-privilege profiles (#289 slice 2). Derive an AgentProfile for a
// fleet agent from its role + ownership globs + the project's discovered toolchain: the
// commands it may auto-run, tools tri-stated by role (a tester can't edit/write), and the
// file-write scope limited to what it owns. Saved with category "generated" / origin
// "generated by Planner" -- the category the model already reserves. Pure + testable.
import type { AgentProfile, Tier, ToolKey } from "../../screens/agents/agentProfiles";
import type { SessionRole } from "./sessionRoles";
import type { AgentStream } from "../../screens/planner/stages/planSections";

/** Per-tool policy by role -- least privilege: doers edit/write/run, checkers read + run,
 *  coordinators mostly read. (`bash` is never blanket-denied; command control is the
 *  allowlist -- see profileEnforcement.) */
const TOOLS_BY_ROLE: Record<SessionRole, Record<ToolKey, Tier>> = {
  worker:    { read: "allow", grep: "allow", glob: "allow", edit: "allow", write: "allow", bash: "allow", web: "ask",  task: "deny"  }, // #1036: a worker does its issue directly, never spawns sub-agents

  planner:   { read: "allow", grep: "allow", glob: "allow", edit: "ask",   write: "ask",   bash: "ask",   web: "ask",  task: "allow" },
  director:  { read: "allow", grep: "allow", glob: "allow", edit: "deny",  write: "deny",  bash: "ask",   web: "ask",  task: "allow" },
  triage:    { read: "allow", grep: "allow", glob: "allow", edit: "ask",   write: "ask",   bash: "ask",   web: "ask",  task: "allow" },
  tester:    { read: "allow", grep: "allow", glob: "allow", edit: "deny",  write: "deny",  bash: "allow", web: "deny", task: "allow" },
  reviewer:  { read: "allow", grep: "allow", glob: "allow", edit: "deny",  write: "deny",  bash: "ask",   web: "deny", task: "allow" },
  conductor: { read: "allow", grep: "allow", glob: "allow", edit: "deny",  write: "deny",  bash: "ask",   web: "deny", task: "allow" },
  // #376 issuer -- intake only: read + shape, open issues via gh (bash ask), never edit code.
  issuer:    { read: "allow", grep: "allow", glob: "allow", edit: "deny",  write: "deny",  bash: "ask",   web: "ask",  task: "allow" },
  // #394 juror -- read-only reviewer that judges a landing; never edits or merges.
  juror:     { read: "allow", grep: "allow", glob: "allow", edit: "deny",  write: "deny",  bash: "ask",   web: "deny", task: "allow" },
};

/** Whether a tool policy permits any file modification. */
function canWrite(tools: Record<ToolKey, Tier>): boolean {
  return tools.edit !== "deny" || tools.write !== "deny";
}

/**
 * Generate a least-privilege AgentProfile for `stream` running as `role`, scoped to the
 * project's `discoveredCommands` (its toolchain). The result is a "generated by Planner"
 * profile the user can accept or tweak; its id is then assigned to the stream's `profile`.
 */
export function generateAgentProfile(
  stream: AgentStream,
  role: SessionRole,
  discoveredCommands: string[],
): AgentProfile {
  const tools = TOOLS_BY_ROLE[role];
  const commands = [...new Set(discoveredCommands.map((c) => c.trim()).filter(Boolean))].sort();
  const owns = canWrite(tools) ? [...stream.owns] : [];
  return {
    id: `gen_${stream.id}`,
    name: `${stream.name} (generated)`,
    color: "oklch(0.7 0.1 250)",
    category: "generated",
    origin: "generated by Planner",
    desc: `Least-privilege for ${stream.name} — ${role}; ${commands.length} project command(s)${owns.length ? `; writes ${owns.join(", ")}` : "; read-only"}.`,
    mode: "ask",
    commands,
    tools,
    paths: { allow: owns, deny: [] },
    net: { allow: [] },
  };
}

/**
 * Whether every fleet stream has a least-privilege profile ASSIGNED that actually exists —
 * the permissions-stage gate (#696). Keyed off `stream.profile` (the assigned profile id,
 * e.g. `gen_<stream>`), NOT the stream id: an earlier bug compared `profile.id === stream.id`,
 * which the real generation flow never produces, so the gate could never pass.
 */
export function fleetProfilesComplete(
  streams: AgentStream[], profiles: { id: string }[],
): boolean {
  return streams.length > 0
    && streams.every((st) => !!st.profile && profiles.some((p) => p.id === st.profile));
}
