import { describe, it, expect } from "vitest";
import { generateAgentProfile, fleetProfilesComplete } from "./profileGen";
import type { AgentStream } from "@/features/planner/stages/planSections";

describe("fleetProfilesComplete — the permissions gate (#696)", () => {
  const s = (id: string, profile?: string): AgentStream =>
    ({ id, name: id, repo: "o/r", owns: [], issues: [], dependsOn: [], profile });

  it("false with no streams", () => {
    expect(fleetProfilesComplete([], [{ id: "gen_a" }])).toBe(false);
  });

  it("false when a stream has no assigned profile (the studio-code case)", () => {
    expect(fleetProfilesComplete([s("a"), s("b")], [{ id: "gen_a" }])).toBe(false);
  });

  it("false for a dangling reference (profile id doesn't exist)", () => {
    expect(fleetProfilesComplete([s("a", "gen_a")], [{ id: "other" }])).toBe(false);
  });

  it("true when every stream's assigned profile exists — keyed on st.profile, not st.id", () => {
    // the previous bug compared profile.id === stream.id ("a"), which never matches gen_a
    expect(fleetProfilesComplete([s("a", "gen_a"), s("b", "pf_build")], [{ id: "gen_a" }, { id: "pf_build" }])).toBe(true);
  });
});

const stream: AgentStream = {
  id: "be", name: "API backend", repo: "o/api",
  owns: ["src/api/**", "src/db/**"], issues: ["#1"], dependsOn: [],
};

describe("generateAgentProfile (#289)", () => {
  it("a worker can edit/write, scoped to its owned globs, with the toolchain", () => {
    const p = generateAgentProfile(stream, "worker", ["cargo", "npm", "cargo"]);
    expect(p).toMatchObject({ id: "gen_be", category: "generated", origin: "generated by Planner", mode: "ask" });
    expect(p.commands).toEqual(["cargo", "npm"]);          // deduped + sorted
    expect(p.tools.edit).toBe("allow");
    expect(p.tools.write).toBe("allow");
    expect(p.paths.allow).toEqual(["src/api/**", "src/db/**"]); // write scope = owns
  });

  it("a tester is read-only: no edit/write, no write paths, but may run the toolchain", () => {
    const p = generateAgentProfile(stream, "tester", ["npm test"]);
    expect(p.tools.edit).toBe("deny");
    expect(p.tools.write).toBe("deny");
    expect(p.tools.bash).toBe("allow");   // runs tests
    expect(p.paths.allow).toEqual([]);    // read-only ⇒ no write scope
    expect(p.commands).toEqual(["npm test"]);
  });

  it("trims/dedupes/sorts the discovered commands and tolerates empties", () => {
    const p = generateAgentProfile(stream, "worker", [" npm ", "npm", "", "cargo"]);
    expect(p.commands).toEqual(["cargo", "npm"]);
  });
});
