// The stage bodies' graph-platform surface (#4230, epic #3604) — AUTO-GENERATED by
// scripts/gen-bodies-graph.cjs. DO NOT EDIT BY HAND: it is derived from the specifiers the bodies'
// records actually carry, so it cannot drift from them. Re-run the generator after changing a body.
//
// Registered HERE, inside the feature, because the shell must not reach a feature's internals (#1545).
//
// The bodies' OWN modules are registered too: each is `provides`-resolved from the graph first, and the
// module behind it is the fallback for a record that will not load. That is also why the eleven
// registrations `pane/graphPlatform.ts` (#4227) makes for these same specifiers are not a conflict —
// `provides` wins over the registry by design, so those become the fallback rather than the route.
import { registerAppModule } from "@/shared/lib/runtime/moduleRegistry";
import * as Personas from "@/features/personas";
import * as DeployView from "@/features/planner/bodies/DeployView";
import * as FocusedPermissionsBody from "@/features/planner/bodies/FocusedPermissionsBody";
import * as FocusedPlanBody from "@/features/planner/bodies/FocusedPlanBody";
import * as ScanViews from "@/features/planner/bodies/ScanViews";
import * as SharedDependencies from "@/features/planner/bodies/SharedDependencies";
import * as StreamFocusCards from "@/features/planner/bodies/StreamFocusCards";
import * as BodyPrimitives from "@/features/planner/bodies/bodyPrimitives";
import * as BodyStyles from "@/features/planner/bodies/bodyStyles";
import * as CollapsibleCard from "@/features/planner/bodies/collapsibleCard";
import * as ConnectorForm from "@/features/planner/bodies/connectorForm";
import * as DataCollection from "@/features/planner/bodies/dataCollection";
import * as DeployPrimitives from "@/features/planner/bodies/deployPrimitives";
import * as DeployShipSections from "@/features/planner/bodies/deployShipSections";
import * as DeployTargetSection from "@/features/planner/bodies/deployTargetSection";
import * as FocusedHandlers from "@/features/planner/bodies/focusedHandlers";
import * as SourceConnection from "@/features/planner/bodies/sourceConnection";
import * as DirectorDrive from "@/features/planner/fleet/directorDrive";
import * as Dependencies from "@/features/planner/issues/dependencies";
import * as FeatureList from "@/features/planner/issues/featureList";
import * as DataModelDerivation from "@/features/planner/lib/dataModelDerivation";
import * as DeployConfig from "@/features/planner/lib/deployConfig";
import * as DropFiles from "@/features/planner/lib/dropFiles";
import * as FileIntake from "@/features/planner/lib/fileIntake";
import * as MarketConfig from "@/features/planner/lib/marketConfig";
import * as SourceConfig from "@/features/planner/lib/sourceConfig";
import * as SourceDiscovery from "@/features/planner/lib/sourceDiscovery";
import * as Transformations from "@/features/planner/lib/transformations";
import * as FocusedPrimitives from "@/features/planner/pane/focusedPrimitives";
import * as ProjectPanetypes from "@/features/planner/pane/projectPane.types";
import * as ProjectPaneData from "@/features/planner/pane/projectPaneData";
import * as StageScreenFrame from "@/features/planner/preview/StageScreenFrame";
import * as StageScreens from "@/features/planner/preview/stageScreens";
import * as RelationshipGraphView from "@/features/planner/relationship/RelationshipGraphView";
import * as RelationshipInspector from "@/features/planner/relationship/RelationshipInspector";
import * as RelationshipGraph from "@/features/planner/relationship/relationshipGraph";

let done = false;

/** Register the stage bodies' injected graph-platform modules. Idempotent. */
export function registerBodiesPlatform(): void {
  if (done) return;
  done = true;
  registerAppModule("@/features/personas", Personas);
  registerAppModule("@/features/planner/bodies/DeployView", DeployView);
  registerAppModule("@/features/planner/bodies/FocusedPermissionsBody", FocusedPermissionsBody);
  registerAppModule("@/features/planner/bodies/FocusedPlanBody", FocusedPlanBody);
  registerAppModule("@/features/planner/bodies/ScanViews", ScanViews);
  registerAppModule("@/features/planner/bodies/SharedDependencies", SharedDependencies);
  registerAppModule("@/features/planner/bodies/StreamFocusCards", StreamFocusCards);
  registerAppModule("@/features/planner/bodies/bodyPrimitives", BodyPrimitives);
  registerAppModule("@/features/planner/bodies/bodyStyles", BodyStyles);
  registerAppModule("@/features/planner/bodies/collapsibleCard", CollapsibleCard);
  registerAppModule("@/features/planner/bodies/connectorForm", ConnectorForm);
  registerAppModule("@/features/planner/bodies/dataCollection", DataCollection);
  registerAppModule("@/features/planner/bodies/deployPrimitives", DeployPrimitives);
  registerAppModule("@/features/planner/bodies/deployShipSections", DeployShipSections);
  registerAppModule("@/features/planner/bodies/deployTargetSection", DeployTargetSection);
  registerAppModule("@/features/planner/bodies/focusedHandlers", FocusedHandlers);
  registerAppModule("@/features/planner/bodies/sourceConnection", SourceConnection);
  registerAppModule("@/features/planner/fleet/directorDrive", DirectorDrive);
  registerAppModule("@/features/planner/issues/dependencies", Dependencies);
  registerAppModule("@/features/planner/issues/featureList", FeatureList);
  registerAppModule("@/features/planner/lib/dataModelDerivation", DataModelDerivation);
  registerAppModule("@/features/planner/lib/deployConfig", DeployConfig);
  registerAppModule("@/features/planner/lib/dropFiles", DropFiles);
  registerAppModule("@/features/planner/lib/fileIntake", FileIntake);
  registerAppModule("@/features/planner/lib/marketConfig", MarketConfig);
  registerAppModule("@/features/planner/lib/sourceConfig", SourceConfig);
  registerAppModule("@/features/planner/lib/sourceDiscovery", SourceDiscovery);
  registerAppModule("@/features/planner/lib/transformations", Transformations);
  registerAppModule("@/features/planner/pane/focusedPrimitives", FocusedPrimitives);
  registerAppModule("@/features/planner/pane/projectPane.types", ProjectPanetypes);
  registerAppModule("@/features/planner/pane/projectPaneData", ProjectPaneData);
  registerAppModule("@/features/planner/preview/StageScreenFrame", StageScreenFrame);
  registerAppModule("@/features/planner/preview/stageScreens", StageScreens);
  registerAppModule("@/features/planner/relationship/RelationshipGraphView", RelationshipGraphView);
  registerAppModule("@/features/planner/relationship/RelationshipInspector", RelationshipInspector);
  registerAppModule("@/features/planner/relationship/relationshipGraph", RelationshipGraph);
}
