import { useState, useEffect, useMemo } from "react";
import { useAppStore } from "@/store";
import { timeAgo } from "@/shared/lib/core/format";
import { Avatar } from "@/shared/ui/data/Avatar";
import { Chip } from "@/shared/ui/data/Chip";
import { ColorSwatch } from "@/shared/ui/controls/ColorSwatch";
import { githubRequest, githubGraphql } from "@/shared/lib/github/github";
import { parseProjectIteration, type BurndownResult, type ProjectIterationNode } from "../github/burndown";
import type { GHEvent, GhMilestone, GhIssueItem as GhIssue } from "@/shared/lib/github/types";
import { PROJECTS_SUMMARY_QUERY, PROJECT_ITERATION_QUERY } from "./projectsSummaryQueries";
import { Spark } from "@/shared/ui/charts";
import {
  computeAllocation,
  computeVelocity,
  computeUpcomingMilestones,
  computeProjectStats,
  countOpenIssues,
  countMilestonesDueSoon,
  countLinkedRepos,
  avgWeeklyClosed,
  type GhProject,
} from "./projectsSummaryDerive";
import { IterationBurnDown } from "./IterationBurnDown";
import { CrossProjectActivity } from "./CrossProjectActivity";

// ── Data hook ─────────────────────────────────────────────────────────────────

function useProjectsSummaryData() {
  const { githubToken, githubUser } = useAppStore();
  const [loading, setLoading] = useState(false);
  const [projects, setProjects] = useState<GhProject[]>([]);
  const [events, setEvents] = useState<GHEvent[]>([]);
  const [repoMilestones, setRepoMilestones] = useState<Record<string, GhMilestone[]>>({});
  const [repoIssues, setRepoIssues] = useState<Record<string, GhIssue[]>>({});
  const [burndown, setBurndown] = useState<BurndownResult | null>(null);

  useEffect(() => {
    if (!githubToken || !githubUser) return;
    const login = githubUser.login;
    setLoading(true);

    const projectsP = githubGraphql<{ viewer: { projectsV2: { nodes: GhProject[] } } }>(PROJECTS_SUMMARY_QUERY, null)
      .then(d => d?.viewer?.projectsV2?.nodes ?? []).catch((): GhProject[] => []);

    const eventsP = githubRequest<GHEvent[]>(`users/${login}/events?per_page=100`).catch((): GHEvent[] => []);

    Promise.all([projectsP, eventsP]).then(([projs, evts]) => {
      const projArr = Array.isArray(projs) ? projs : [];
      const evtArr = Array.isArray(evts) ? evts : [];
      setProjects(projArr);
      setEvents(evtArr);

      // Iteration burn-down for the lead project (first active with items): pull
      // its Iteration/Status fields + items and resolve the current iteration.
      const lead = projArr.find(p => !p.closed && p.items.totalCount > 0);
      if (lead) {
        githubGraphql<{ node: ProjectIterationNode | null }>(PROJECT_ITERATION_QUERY, { projectId: lead.id })
          .then(d => setBurndown(parseProjectIteration(d?.node ?? null, Date.now())))
          .catch(() => setBurndown({ status: "no-field" }));
      } else {
        setBurndown({ status: "no-field" });
      }

      // Collect unique repos from all projects
      const slugSet = new Set<string>();
      projArr.forEach(p => p.repositories.nodes.forEach(r => slugSet.add(r.nameWithOwner)));
      const slugs = Array.from(slugSet).slice(0, 6);

      if (slugs.length === 0) { setLoading(false); return; }

      const eightWeeksAgo = new Date(Date.now() - 56 * 86400000).toISOString();

      Promise.all(slugs.map(slug => Promise.all([
        githubRequest<GhMilestone[]>(
          `repos/${slug}/milestones?state=open&sort=due_on&direction=asc&per_page=10`,
        ).catch((): GhMilestone[] => []),
        githubRequest<GhIssue[]>(
          `repos/${slug}/issues?state=all&per_page=100&sort=created&direction=desc&since=${eightWeeksAgo}`,
        ).catch((): GhIssue[] => []),
      ]))).then(results => {
        const ms: Record<string, GhMilestone[]> = {};
        const is: Record<string, GhIssue[]> = {};
        slugs.forEach((slug, i) => {
          const [milestones, issues] = results[i] as [GhMilestone[], GhIssue[]];
          ms[slug] = Array.isArray(milestones) ? milestones : [];
          is[slug] = Array.isArray(issues) ? issues : [];
        });
        setRepoMilestones(ms);
        setRepoIssues(is);
        setLoading(false);
      }).catch(() => setLoading(false));
    }).catch(() => setLoading(false));
  }, [githubToken, githubUser?.login]); // eslint-disable-line react-hooks/exhaustive-deps

  return { loading, projects, events, repoMilestones, repoIssues, burndown };
}

// ── Shared sub-components ─────────────────────────────────────────────────────

// ── AI weekly digest (static — generated by Claude) ───────────────────────────

function AISummary() {
  return (
    <div className="card" style={{
      padding: "14px 18px",
      background: "linear-gradient(135deg, color-mix(in oklch, var(--accent), transparent 88%), var(--bg-panel) 60%)",
      border: "1px solid var(--accent-dim)",
    }}>
      <div style={{ display: "flex", gap: 12 }}>
        <div style={{
          flexShrink: 0, width: 28, height: 28, borderRadius: 7,
          background: "linear-gradient(135deg, var(--accent), oklch(0.62 0.14 50))",
          color: "#1a120a", fontFamily: "var(--mono)", fontWeight: 700, fontSize: 13,
          display: "flex", alignItems: "center", justifyContent: "center",
        }}>C</div>
        <div style={{ flex: 1, fontSize: 12, lineHeight: 1.6, color: "var(--fg-muted)" }}>
          <div style={{ display: "flex", alignItems: "baseline", gap: 8, marginBottom: 4 }}>
            <span style={{ fontFamily: "var(--mono)", fontSize: 11, color: "var(--accent)", textTransform: "uppercase", letterSpacing: ".06em" }}>
              weekly digest · claude
            </span>
            <span className="hint">generated 02:00 today · run #14</span>
            <div style={{ flex: 1 }} />
            <button className="btn ghost" style={{ height: 22, fontSize: 10 }}>regenerate</button>
          </div>
          <p style={{ margin: 0 }}>
            Portfolio is on track — active projects are progressing against open milestones.
            Cross-project activity shows consistent momentum. Check upcoming milestones
            and velocity trends below for details.
          </p>
        </div>
      </div>
    </div>
  );
}

// ── Where the team is (project allocation) ────────────────────────────────────

function ProjectAllocation({ projects }: { projects: GhProject[] }) {
  const items = computeAllocation(projects);

  if (items.length === 0) {
    return (
      <div className="card" style={{ padding: "14px 16px" }}>
        <h3 style={{ margin: 0, marginBottom: 10 }}>Where the team is</h3>
        <div style={{ fontFamily: "var(--mono)", fontSize: 11, color: "var(--fg-dim)" }}>No active projects with items.</div>
      </div>
    );
  }

  return (
    <div className="card" style={{ padding: "14px 16px" }}>
      <div style={{ display: "flex", alignItems: "baseline", gap: 10, marginBottom: 10 }}>
        <h3 style={{ margin: 0 }}>Where the team is</h3>
        <span className="hint">share of in-progress work by project items</span>
      </div>
      <div style={{ display: "flex", height: 10, borderRadius: 5, overflow: "hidden", background: "var(--bg-elev2)", marginBottom: 12 }}>
        {items.map(it => (
          <div key={it.n} title={`${it.n} · ${it.pct}%`} style={{ width: `${it.pct}%`, background: it.c }} />
        ))}
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: 5, fontFamily: "var(--mono)", fontSize: 10.5, color: "var(--fg-muted)" }}>
        {items.map(it => (
          <div key={it.n} style={{ display: "grid", gridTemplateColumns: "12px 1fr 40px", gap: 8, alignItems: "center" }}>
            <ColorSwatch color={it.c} />
            <span style={{ color: "var(--fg)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{it.n}</span>
            <span style={{ textAlign: "right", color: "var(--fg-dim)" }}>{it.pct}%</span>
          </div>
        ))}
      </div>
    </div>
  );
}

// ── Velocity ──────────────────────────────────────────────────────────────────

function VelocityCard({ repoIssues, loading }: {
  repoIssues: Record<string, GhIssue[]>;
  loading: boolean;
}) {
  const { opened, closed, weekLabels, avgClosed } = useMemo(() => computeVelocity(repoIssues), [repoIssues]);

  const hasData = Object.keys(repoIssues).length > 0;
  const maxV = Math.max(...opened, ...closed, 1);

  return (
    <div className="card" style={{ padding: "14px 16px" }}>
      <div style={{ display: "flex", alignItems: "baseline", gap: 10, marginBottom: 10 }}>
        <h3 style={{ margin: 0 }}>Velocity</h3>
        <span className="hint">{loading ? "loading…" : hasData ? "issues opened vs closed · last 8 weeks" : "no data"}</span>
      </div>
      {!hasData && !loading && (
        <div style={{ fontFamily: "var(--mono)", fontSize: 11, color: "var(--fg-dim)", padding: "4px 0" }}>No issue data available.</div>
      )}
      {(hasData || loading) && (
        <>
          <svg width="100%" height="100" viewBox="0 0 320 100">
            {[0, Math.round(maxV * 0.25), Math.round(maxV * 0.5), Math.round(maxV * 0.75), maxV].map(v => (
              <line key={v} x1={30} y1={90 - (v / maxV) * 80} x2={310} y2={90 - (v / maxV) * 80}
                stroke="var(--border-soft)" strokeDasharray="2 3" />
            ))}
            {weekLabels.map((w, i) => {
              const cx = 30 + (i / (weekLabels.length - 1)) * 280;
              const colW = 14;
              const oH = (opened[i] / maxV) * 80;
              const cH = (closed[i] / maxV) * 80;
              return (
                <g key={w}>
                  <rect x={cx - colW} y={90 - oH} width={colW - 1} height={oH}
                    fill="color-mix(in oklch, var(--info), transparent 50%)" />
                  <rect x={cx + 1} y={90 - cH} width={colW - 1} height={cH}
                    fill="var(--accent)" />
                  <text x={cx} y={99} textAnchor="middle" fontFamily="var(--mono)" fontSize="8" fill="var(--fg-dim)">{w}</text>
                </g>
              );
            })}
          </svg>
          <div style={{ display: "flex", gap: 14, marginTop: 6, fontFamily: "var(--mono)", fontSize: 10, color: "var(--fg-muted)" }}>
            <span><ColorSwatch color="color-mix(in oklch, var(--info), transparent 50%)" /> opened</span>
            <span><ColorSwatch color="var(--accent)" /> closed</span>
            <div style={{ flex: 1 }} />
            <span>avg <b style={{ color: "var(--fg)" }}>{loading ? "…" : `${avgClosed} closed/wk`}</b></span>
          </div>
        </>
      )}
    </div>
  );
}

// ── Upcoming milestones ───────────────────────────────────────────────────────

function UpcomingMilestones({ repoMilestones, loading }: {
  repoMilestones: Record<string, GhMilestone[]>;
  loading: boolean;
}) {
  const upcoming = useMemo(() => computeUpcomingMilestones(repoMilestones), [repoMilestones]);

  const hasData = Object.keys(repoMilestones).length > 0;
  const numLines = upcoming.length;

  return (
    <div className="card" style={{ padding: "14px 16px" }}>
      <div style={{ display: "flex", alignItems: "baseline", gap: 10, marginBottom: 14 }}>
        <h3 style={{ margin: 0 }}>Upcoming milestones</h3>
        <span className="hint">{loading ? "loading…" : hasData ? `across all project repos · 8-week view` : "no data"}</span>
        <div style={{ flex: 1 }} />
        {upcoming.length > 0 && (
          <span style={{ fontFamily: "var(--mono)", fontSize: 10.5, color: "var(--accent)" }}>
            {upcoming.length} due in next 8w
          </span>
        )}
      </div>

      {!hasData && !loading && (
        <div style={{ fontFamily: "var(--mono)", fontSize: 11, color: "var(--fg-dim)", padding: "4px 0" }}>No milestones due in the next 8 weeks.</div>
      )}

      {(hasData || loading) && (
        <>
          <div style={{ display: "grid", gridTemplateColumns: "220px 1fr", gap: 14, marginBottom: 8 }}>
            <div />
            <div style={{ position: "relative", height: 18, display: "grid", gridTemplateColumns: "repeat(8, 1fr)" }}>
              {Array.from({ length: 8 }, (_, i) => (
                <div key={i} style={{
                  fontFamily: "var(--mono)", fontSize: 9.5, color: "var(--fg-dim)",
                  borderLeft: i === 0 ? "none" : "1px dashed var(--border-soft)",
                  paddingLeft: 6, paddingTop: 2,
                }}>w{i + 1}</div>
              ))}
              <div style={{
                position: "absolute", top: 0, bottom: -(numLines * 30 + 10),
                left: 0, width: 0,
                borderLeft: "1.5px dashed var(--accent)", zIndex: 2,
              }}>
                <span style={{ position: "absolute", top: -2, left: 4, fontFamily: "var(--mono)", fontSize: 9.5, color: "var(--accent)" }}>today</span>
              </div>
            </div>
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
            {upcoming.map((m, idx) => {
              const barEnd = Math.max(0.01, Math.min(8, m.weeksFromNow));
              const barStart = Math.max(0, barEnd - 0.7);
              const c = m.overdue ? "var(--danger)" : "var(--accent)";
              const bgC = m.overdue ? "oklch(0.65 0.15 10)" : "oklch(0.78 0.14 70)";
              return (
                <div key={idx} style={{ display: "grid", gridTemplateColumns: "220px 1fr", gap: 14, alignItems: "center" }}>
                  <div>
                    <div style={{ fontFamily: "var(--mono)", fontSize: 10.5, color: m.overdue ? "var(--danger)" : "var(--accent)" }}>{m.title}</div>
                    <div style={{ fontFamily: "var(--mono)", fontSize: 9.5, color: "var(--fg-dim)" }}>{m.repo}</div>
                  </div>
                  <div style={{ position: "relative", height: 24 }}>
                    {Array.from({ length: 8 }, (_, i) => (
                      <div key={i} style={{ position: "absolute", top: 0, bottom: 0, left: `${i / 8 * 100}%`, width: 1, background: "var(--border-soft)" }} />
                    ))}
                    <div style={{
                      position: "absolute", top: 3, bottom: 3,
                      left: `${barStart / 8 * 100}%`, width: `${(barEnd - barStart) / 8 * 100}%`,
                      minWidth: 12, borderRadius: 4,
                      background: `color-mix(in oklch, ${bgC}, transparent 65%)`,
                      border: `1px solid ${c}`,
                      overflow: "hidden",
                    }}>
                      {m.pct > 0 && (
                        <div style={{ position: "absolute", inset: 0, width: `${m.pct * 100}%`, background: `color-mix(in oklch, ${bgC}, transparent 30%)` }} />
                      )}
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </>
      )}
    </div>
  );
}

// ── Risk register (manual — from plan sessions) ───────────────────────────────

interface Risk { sev: "high" | "med" | "low"; proj: string; r: string; own: string }

function RiskRegister() {
  // Risks are logged manually during planning sessions; no live source is wired yet (#…), so this
  // renders an honest empty state until one is — never fabricated entries.
  const risks: Risk[] = [];
  const med = risks.filter(r => r.sev === "med").length;
  const low = risks.filter(r => r.sev === "low").length;
  return (
    <div className="card" style={{ padding: "14px 16px" }}>
      <div style={{ display: "flex", alignItems: "baseline", gap: 10, marginBottom: 10 }}>
        <h3 style={{ margin: 0 }}>Risk register</h3>
        <span className="hint">{risks.length ? `${med} medium · ${low} low across active projects` : "logged during planning"}</span>
        <div style={{ flex: 1 }} />
        {risks.length > 0 && <button className="btn ghost" style={{ height: 24, fontSize: 10.5 }}>view all</button>}
      </div>
      {risks.length === 0 ? (
        <div style={{ padding: "18px 12px", textAlign: "center", fontFamily: "var(--mono)", fontSize: 11, color: "var(--fg-dim)" }}>
          No risks logged yet.
        </div>
      ) : (
        <div style={{ borderRadius: 6, border: "1px solid var(--border-soft)", overflow: "hidden" }}>
          <div style={{
            display: "grid", gridTemplateColumns: "50px 110px 1fr 60px",
            gap: 8, padding: "7px 12px",
            background: "var(--bg-elev2)", borderBottom: "1px solid var(--border-soft)",
            fontFamily: "var(--mono)", fontSize: 10, color: "var(--fg-dim)",
            textTransform: "uppercase", letterSpacing: ".06em",
          }}>
            <span>sev</span><span>project</span><span>risk</span><span>owner</span>
          </div>
          {risks.map((r, i) => (
            <div key={i} style={{
              display: "grid", gridTemplateColumns: "50px 110px 1fr 60px",
              gap: 8, padding: "8px 12px", alignItems: "center",
              background: i % 2 ? "var(--bg-panel)" : "var(--bg-elev)",
              borderTop: i === 0 ? "0" : "1px solid var(--border-soft)",
              fontSize: 11.5,
            }}>
              <span style={{ fontFamily: "var(--mono)", fontSize: 10, color: r.sev === "high" ? "var(--danger)" : r.sev === "med" ? "var(--accent)" : "var(--fg-dim)" }}>
                ● {r.sev}
              </span>
              <span style={{ fontFamily: "var(--mono)", fontSize: 10.5, color: "var(--fg-muted)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" }}>{r.proj}</span>
              <span style={{ color: "var(--fg)" }}>{r.r}</span>
              <Avatar login={r.own} />
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

// ── Projects grid ─────────────────────────────────────────────────────────────

function ProjectsGrid({ projects, repoIssues, loading }: {
  projects: GhProject[];
  repoIssues: Record<string, GhIssue[]>;
  loading: boolean;
}) {
  const { setProjectsPageMode, setWorkspace, setActiveProjectMeta, openGithubBoard } = useAppStore();
  // This portfolio lives in the GitHub screen (#421); "view list" jumps to the
  // Projects tab for planning, while opening a card shows that project's board
  // right here on the GitHub page (#498).
  const openProjects = () => { setWorkspace("projects"); setProjectsPageMode("projects"); };
  const openBoard = (p: GhProject) => {
    const repos = p.repositories?.nodes?.map(r => r.nameWithOwner) ?? [];
    setActiveProjectMeta(p.id, p.title, repos[0] ?? "", p.number, repos);
    openGithubBoard("board");
  };

  const projectsWithStats = useMemo(
    () => computeProjectStats(projects, repoIssues),
    [projects, repoIssues],
  );

  return (
    <div className="card" style={{ padding: "14px 16px" }}>
      <div style={{ display: "flex", alignItems: "baseline", gap: 10, marginBottom: 10 }}>
        <h3 style={{ margin: 0 }}>Projects</h3>
        <span className="hint">{loading ? "loading…" : `${projects.length} project${projects.length !== 1 ? "s" : ""} · click to open the board`}</span>
        <div style={{ flex: 1 }} />
        <button className="btn ghost" style={{ height: 24, fontSize: 10.5 }}
          onClick={openProjects}>view list →</button>
      </div>
      {projects.length === 0 && !loading && (
        <div style={{ fontFamily: "var(--mono)", fontSize: 11, color: "var(--fg-dim)", padding: "8px 0" }}>No projects found. Create one on GitHub.</div>
      )}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: 8 }}>
        {projectsWithStats.map(({ p, c, status, spark, repo }) => (
          <div key={p.id} onClick={() => openBoard(p)} style={{
            padding: "12px 14px", borderRadius: 6,
            background: "var(--bg-elev)", border: "1px solid var(--border-soft)",
            cursor: "pointer", minWidth: 0, overflow: "hidden",
          }}>
            <div style={{ display: "flex", alignItems: "baseline", gap: 8, marginBottom: 4 }}>
              <ColorSwatch color={c} size={8} />
              <span style={{ fontFamily: "var(--mono)", fontSize: 12, color: "var(--fg)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis", flex: 1 }}>{p.title}</span>
              <Chip tone={status === "active" ? "success" : status === "shipped" ? "neutral" : "accent"} style={{ fontSize: 9 }}>{status}</Chip>
            </div>
            <div style={{ fontFamily: "var(--mono)", fontSize: 10, color: "var(--fg-dim)", marginBottom: 8 }}>
              {repo}
            </div>
            <div style={{ display: "flex", alignItems: "center", gap: 12, fontFamily: "var(--mono)", fontSize: 10, color: "var(--fg-muted)" }}>
              <span><b style={{ color: "var(--fg)" }}>{p.items.totalCount}</b> items</span>
              <span style={{ fontFamily: "var(--mono)", fontSize: 9.5, color: "var(--fg-dim)" }}>{timeAgo(p.updatedAt)}</span>
              <div style={{ flex: 1 }} />
              {spark.some(v => v > 0) && <Spark data={spark} color={c} w={80} h={18} fill={false} dot={false} />}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

// ── Main ──────────────────────────────────────────────────────────────────────

export function ProjectsSummary() {
  const { setProjectsPageMode, setWorkspace } = useAppStore();
  // Hosted in the GitHub screen (#421) — "browse projects" jumps to the Projects tab.
  const openProjects = () => { setWorkspace("projects"); setProjectsPageMode("projects"); };
  const { loading, projects, events, repoMilestones, repoIssues, burndown } = useProjectsSummaryData();

  const activeProjects = projects.filter(p => !p.closed);
  const draftingCount = activeProjects.filter(p => p.items.totalCount === 0).length;
  const activeCount = activeProjects.filter(p => p.items.totalCount > 0).length;
  const shippedCount = projects.filter(p => p.closed).length;

  const totalOpenIssues = useMemo(() => countOpenIssues(repoIssues), [repoIssues]);
  const totalMilestones = useMemo(() => countMilestonesDueSoon(repoMilestones), [repoMilestones]);
  const avgVelocity = useMemo(() => avgWeeklyClosed(repoIssues), [repoIssues]);

  return (
    <section style={{ flex: 1, overflow: "auto", padding: "20px 24px", minWidth: 0, background: "var(--bg-canvas)" }}>
      <div style={{ maxWidth: 1280, margin: "0 auto" }}>
        <div style={{ display: "flex", alignItems: "flex-start", gap: 14, marginBottom: 14 }}>
          <div style={{ flex: 1 }}>
            <h2 style={{ margin: 0, fontFamily: "var(--mono)", fontSize: 20, fontWeight: 600 }}>Portfolio</h2>
            <div style={{ color: "var(--fg-muted)", fontSize: 12, marginTop: 4 }}>
              {loading ? "loading…" : `${activeCount} active · ${draftingCount} drafting · ${shippedCount} shipped`}
            </div>
          </div>
          <button className="btn" onClick={openProjects}>browse projects →</button>
        </div>

        <div style={{ marginBottom: 14 }}>
          <AISummary />
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "repeat(6, 1fr)", gap: 8, marginBottom: 14 }}>
          {([
            ["projects",    loading ? "…" : String(projects.length),    `${activeCount} active · ${draftingCount} drafting`,  "fg"    ],
            ["open issues", loading ? "…" : String(totalOpenIssues),    "across project repos",              "accent" ],
            ["active",      loading ? "…" : String(activeCount),        "in-progress projects",              "info"   ],
            ["velocity",    loading ? "…" : `${avgVelocity}/wk`,        "avg issues closed",                 "muted"  ],
            ["milestones",  loading ? "…" : String(totalMilestones),    "due in next 2 weeks",               "info"   ],
            ["repos",       loading ? "…" : String(countLinkedRepos(projects)), "linked across projects", "muted"],
          ] as const).map(([k, v, sub, tone]) => (
            <div key={k} className="card" style={{ padding: "10px 12px" }}>
              <div style={{ fontFamily: "var(--mono)", fontSize: 10, color: "var(--fg-dim)", textTransform: "uppercase", letterSpacing: ".06em" }}>{k}</div>
              <div style={{
                fontFamily: "var(--mono)", fontSize: 18, fontWeight: 600, marginTop: 2,
                color: tone === "accent" ? "var(--accent)" : tone === "info" ? "var(--info)" : "var(--fg)",
              }}>{v}</div>
              <div style={{ fontSize: 10, color: "var(--fg-muted)", marginTop: 1 }}>{sub}</div>
            </div>
          ))}
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "1.6fr 1fr", gap: 14 }}>
          <div style={{ display: "flex", flexDirection: "column", gap: 14, minWidth: 0 }}>
            <ProjectsGrid projects={projects} repoIssues={repoIssues} loading={loading} />
            <IterationBurnDown data={burndown} loading={loading} />
            <UpcomingMilestones repoMilestones={repoMilestones} loading={loading} />
            <CrossProjectActivity events={events} projects={projects} loading={loading} />
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: 14, minWidth: 0 }}>
            <ProjectAllocation projects={projects} />
            <VelocityCard repoIssues={repoIssues} loading={loading} />
            <RiskRegister />
          </div>
        </div>
      </div>
    </section>
  );
}
