// The themeable kit (#1852 Phases 0/1/3) — public barrel. The semantic component tokens live in
// styles/tokens.css; this module is the THEME axis over them: the registry + apply helpers + the
// scoped wrapper. See also `@/shared/ui/spec` (the SPEC axis — KitNode + KitRenderer).

export type { KitTheme } from "./theme";
export {
  KIT_THEMES, DEFAULT_THEME, KIT_TOKENS, themeById, themeVars, applyThemeToRoot,
  // #2488: the designer-writable theme store's sync hooks — the components slice hydrate pushes the
  // store collection in; every themeById/themeVars/ThemeScope consumer then resolves against it.
  setActiveKitThemes, activeKitThemes, kitTokens,
} from "./theme";
export { ThemeScope } from "./ThemeScope";
export type { ThemeScopeProps } from "./ThemeScope";
// #2569: data-defined component variants — compile the designer-authored variant store into a managed
// `<style>` of `.<component>.<variant>` rules (the render path for `bsc ui component … define-variant`).
export type { VariantDef } from "./variants";
export { compileVariantsCss, applyVariantsToRoot } from "./variants";
// #2867: data-defined component animations — compile authored motion (on a component record) into a
// managed <style> (keyframes + a reduced-motion-guarded applying rule), re-applied on boot + ui-touch.
export type { ComponentAnimation, AnimationDef, AnimationTrigger } from "./animations";
export { compileAnimationsCss, applyAnimationsToRoot, componentAnimations } from "./animations";
// #2650: design-contribution overlay — the compose-don't-mutate application of the tokens a downloaded
// blueprint contributes (reconciled missing categories, generated by #2636), as a managed :root <style>.
export type { DesignContributionOverlay } from "./contributions";
export {
  compileContributionsCss, applyContributionsToRoot, contributionFromCategories, graphCategoryToken,
} from "./contributions";
// #2646: the PURE reconcile diff — a downloaded blueprint's design contribution vs the local contract.
// The confirm-list (#2658) generates + registers a contribution for whatever the contract can't cover.
export type { DesignContribution, DesignReconcile } from "./reconcile";
export { reconcileDesign, KNOWN_GRAPH_CATEGORIES } from "./reconcile";
