// The planning session's graph-platform surface (#4224, epic #3604) — AUTO-GENERATED by
// scripts/gen-planning-graph.cjs. DO NOT EDIT BY HAND: it is derived from what the `planningpage`
// records actually import, so it cannot drift from them. Re-run the generator after changing the page.
//
// These are the modules that RUN the session — the terminal, the tag stream, the gates, the publish
// pipeline, the autopilot, the conductor. The graph carries the arrangement; every one of these stays
// code, registered here so the loaded page's `require()` reaches the live module.
import { registerAppModule } from "@/shared/lib/runtime/moduleRegistry";
import * as BlueprintUpdateModal from "@/features/planner/blueprints/BlueprintUpdateModal";
import * as BlueprintSkills from "@/features/planner/blueprints/blueprintSkills";
import * as AgentFlow from "@/features/planner/fleet/agentFlow";
import * as PlanFleet from "@/features/planner/fleet/planFleet";
import * as WorkerScope from "@/features/planner/fleet/workerScope";
import * as GhStructure from "@/features/planner/github/ghStructure";
import * as Dependencies from "@/features/planner/issues/dependencies";
import * as FeatureList from "@/features/planner/issues/featureList";
import * as PlanFeatures from "@/features/planner/issues/planFeatures";
import * as PlanIssues from "@/features/planner/issues/planIssues";
import * as ClassifyConfig from "@/features/planner/lib/classifyConfig";
import * as DeployConfig from "@/features/planner/lib/deployConfig";
import * as FileIntake from "@/features/planner/lib/fileIntake";
import * as McpPaneData from "@/features/planner/lib/mcpPaneData";
import * as PlanInjection from "@/features/planner/lib/planInjection";
import * as ProjectRepos from "@/features/planner/list/projectRepos";
import * as McpDownloadModal from "@/features/planner/pane/McpDownloadModal";
import * as ProjectPane from "@/features/planner/pane/ProjectPane";
import * as ProjectPaneData from "@/features/planner/pane/projectPaneData";
import * as PlanAutopilotRunner from "@/features/planner/session/planAutopilotRunner";
import * as PlannerConductor from "@/features/planner/session/plannerConductor";
import * as ProjectTitle from "@/features/planner/session/projectTitle";
import * as UseCtxRequired from "@/features/planner/session/useCtxRequired";
import * as UseDesignRouteState from "@/features/planner/session/useDesignRouteState";
import * as UsePlanConfirmations from "@/features/planner/session/usePlanConfirmations";
import * as UsePlanFocusedPane from "@/features/planner/session/usePlanFocusedPane";
import * as UsePlanGates from "@/features/planner/session/usePlanGates";
import * as UsePlanMcpDownloads from "@/features/planner/session/usePlanMcpDownloads";
import * as UsePlanMcpManagement from "@/features/planner/session/usePlanMcpManagement";
import * as UsePlanPublish from "@/features/planner/session/usePlanPublish";
import * as UsePlanSkillsManagement from "@/features/planner/session/usePlanSkillsManagement";
import * as UsePlanStagePoll from "@/features/planner/session/usePlanStagePoll";
import * as UsePlannerBlueprint from "@/features/planner/session/usePlannerBlueprint";
import * as UsePlannerPromptDelivery from "@/features/planner/session/usePlannerPromptDelivery";
import * as UsePlannerRepoManagement from "@/features/planner/session/usePlannerRepoManagement";
import * as UsePlannerTagStream from "@/features/planner/session/usePlannerTagStream";
import * as UsePlannerTerminal from "@/features/planner/session/usePlannerTerminal";
import * as UsePlannerTunnelSync from "@/features/planner/session/usePlannerTunnelSync";
import * as UsePlanningModals from "@/features/planner/session/usePlanningModals";
import * as UsePlanningSession from "@/features/planner/session/usePlanningSession";
import * as UsePlanningTitle from "@/features/planner/session/usePlanningTitle";
import * as UseSetupSignature from "@/features/planner/session/useSetupSignature";
import * as Blueprints from "@/features/planner/stages/blueprints";
import * as ConfirmReconcile from "@/features/planner/stages/confirmReconcile";
import * as FocusedPlan from "@/features/planner/stages/focusedPlan";
import * as PlanStages from "@/features/planner/stages/planStages";
import * as PlanTopics from "@/features/planner/stages/planTopics";

let done = false;

/** Register the Planning session's injected graph-platform modules. Idempotent. */
export function registerPlanningPlatform(): void {
  if (done) return;
  done = true;
  registerAppModule("@/features/planner/blueprints/BlueprintUpdateModal", BlueprintUpdateModal);
  registerAppModule("@/features/planner/blueprints/blueprintSkills", BlueprintSkills);
  registerAppModule("@/features/planner/fleet/agentFlow", AgentFlow);
  registerAppModule("@/features/planner/fleet/planFleet", PlanFleet);
  registerAppModule("@/features/planner/fleet/workerScope", WorkerScope);
  registerAppModule("@/features/planner/github/ghStructure", GhStructure);
  registerAppModule("@/features/planner/issues/dependencies", Dependencies);
  registerAppModule("@/features/planner/issues/featureList", FeatureList);
  registerAppModule("@/features/planner/issues/planFeatures", PlanFeatures);
  registerAppModule("@/features/planner/issues/planIssues", PlanIssues);
  registerAppModule("@/features/planner/lib/classifyConfig", ClassifyConfig);
  registerAppModule("@/features/planner/lib/deployConfig", DeployConfig);
  registerAppModule("@/features/planner/lib/fileIntake", FileIntake);
  registerAppModule("@/features/planner/lib/mcpPaneData", McpPaneData);
  registerAppModule("@/features/planner/lib/planInjection", PlanInjection);
  registerAppModule("@/features/planner/list/projectRepos", ProjectRepos);
  registerAppModule("@/features/planner/pane/McpDownloadModal", McpDownloadModal);
  registerAppModule("@/features/planner/pane/ProjectPane", ProjectPane);
  registerAppModule("@/features/planner/pane/projectPaneData", ProjectPaneData);
  registerAppModule("@/features/planner/session/planAutopilotRunner", PlanAutopilotRunner);
  registerAppModule("@/features/planner/session/plannerConductor", PlannerConductor);
  registerAppModule("@/features/planner/session/projectTitle", ProjectTitle);
  registerAppModule("@/features/planner/session/useCtxRequired", UseCtxRequired);
  registerAppModule("@/features/planner/session/useDesignRouteState", UseDesignRouteState);
  registerAppModule("@/features/planner/session/usePlanConfirmations", UsePlanConfirmations);
  registerAppModule("@/features/planner/session/usePlanFocusedPane", UsePlanFocusedPane);
  registerAppModule("@/features/planner/session/usePlanGates", UsePlanGates);
  registerAppModule("@/features/planner/session/usePlanMcpDownloads", UsePlanMcpDownloads);
  registerAppModule("@/features/planner/session/usePlanMcpManagement", UsePlanMcpManagement);
  registerAppModule("@/features/planner/session/usePlanPublish", UsePlanPublish);
  registerAppModule("@/features/planner/session/usePlanSkillsManagement", UsePlanSkillsManagement);
  registerAppModule("@/features/planner/session/usePlanStagePoll", UsePlanStagePoll);
  registerAppModule("@/features/planner/session/usePlannerBlueprint", UsePlannerBlueprint);
  registerAppModule("@/features/planner/session/usePlannerPromptDelivery", UsePlannerPromptDelivery);
  registerAppModule("@/features/planner/session/usePlannerRepoManagement", UsePlannerRepoManagement);
  registerAppModule("@/features/planner/session/usePlannerTagStream", UsePlannerTagStream);
  registerAppModule("@/features/planner/session/usePlannerTerminal", UsePlannerTerminal);
  registerAppModule("@/features/planner/session/usePlannerTunnelSync", UsePlannerTunnelSync);
  registerAppModule("@/features/planner/session/usePlanningModals", UsePlanningModals);
  registerAppModule("@/features/planner/session/usePlanningSession", UsePlanningSession);
  registerAppModule("@/features/planner/session/usePlanningTitle", UsePlanningTitle);
  registerAppModule("@/features/planner/session/useSetupSignature", UseSetupSignature);
  registerAppModule("@/features/planner/stages/blueprints", Blueprints);
  registerAppModule("@/features/planner/stages/confirmReconcile", ConfirmReconcile);
  registerAppModule("@/features/planner/stages/focusedPlan", FocusedPlan);
  registerAppModule("@/features/planner/stages/planStages", PlanStages);
  registerAppModule("@/features/planner/stages/planTopics", PlanTopics);
}
